var gvjs_rQ="#990000",gvjs_sQ="annotationText",gvjs_tQ="certainty",gvjs_uQ="chartType",gvjs_vQ="col-resize";function gvjs_wQ(a,b){var c=new gvjs_N,d=b.aa(),e=b.Z(),f=a.Y(0)!=gvjs_c;f&&c.qe(a.Y(0),a.Ca(0));for(var g=f?1:0,h=g;h<e;++h)c.qe({type:a.Y(h),label:a.Ca(h),role:gvjs_0t}),c.qe({type:b.Y(h),label:b.Ca(h),role:gvjs_pr});c.Sp(d);for(var k=0;k<d;++k){f&&(h=b.getValue(k,0),c.nc(k,0,h));var l=g;for(h=g;h<e;++h){var m=a.getValue(k,h);c.nc(k,l,m);l+=1;m=b.getValue(k,h);c.nc(k,l,m);l+=1}}return c}
gvjs_xK.prototype.jq=gvjs_B(65,function(a,b){if(this.lh===gvjs_eu)return gvjs_wQ(a,b);throw Error("Cannot compute diff for this chart type.");});gvjs_yK.prototype.jq=gvjs_B(64,function(a,b){return gvjs_wQ(a,b)});gvjs_1z.prototype.jA=gvjs_B(44,function(){});gvjs_fA.prototype.jA=gvjs_B(43,function(a,b){a.setAttribute("y",b)});gvjs_jA.prototype.jA=gvjs_B(42,function(a,b){a.style.top=this.Zb(b)});gvjs_1z.prototype.fA=gvjs_B(41,function(){});
gvjs_fA.prototype.fA=gvjs_B(40,function(a,b){a.setAttribute("x",b)});gvjs_jA.prototype.fA=gvjs_B(39,function(a,b){a.style.left=this.Zb(b)});function gvjs_xQ(a,b){var c=gvjs_ux(a,b);if(0<=c)return b;c=-(c+1);if(0==c)return a[0];if(c==a.length)return gvjs_Sh(a);var d=a[c-1];a=a[c];return Math.abs(b-d)<=Math.abs(b-a)?d:a}function gvjs_yQ(a){var b=new gvjs_rD;b.ra=function(){return a};return b}function gvjs_zQ(a){gvjs_xK.call(this,a);this.Zd(gvjs_a,gvjs_7p,gvjs_Z)}gvjs_l(gvjs_zQ,gvjs_xK);
function gvjs_AQ(a){gvjs_xK.call(this,a);this.Zd(gvjs_a,gvjs_kv,gvjs_Z)}gvjs_l(gvjs_AQ,gvjs_xK);function gvjs_BQ(a){gvjs_xK.call(this,a);this.Zd(gvjs_a,gvjs_b,gvjs_Z,"sparkline")}gvjs_l(gvjs_BQ,gvjs_xK);function gvjs_CQ(a){gvjs_xK.call(this,a);this.Zd(gvjs_a,gvjs_w,gvjs_Z)}gvjs_l(gvjs_CQ,gvjs_xK);function gvjs_DQ(a){gvjs_xK.call(this,a);this.Zd(gvjs_Xg)}gvjs_l(gvjs_DQ,gvjs_xK);gvjs_DQ.prototype.jq=function(a,b){return gvjs_wQ(a,b)};function gvjs_EQ(a){gvjs_xK.call(this,a);this.Zd(gvjs_xq)}
gvjs_l(gvjs_EQ,gvjs_xK);function gvjs_FQ(a){gvjs_xK.call(this,a);this.Zd(gvjs_a,gvjs_hq,gvjs_1)}gvjs_l(gvjs_FQ,gvjs_xK);gvjs_FQ.prototype.jq=function(a,b){return gvjs_wQ(a,b)};function gvjs_GQ(a){gvjs_xK.call(this,a);this.Zd(gvjs_a,gvjs_Eq,gvjs_Z)}gvjs_l(gvjs_GQ,gvjs_xK);function gvjs_HQ(a){gvjs_xK.call(this,a);this.Zd(gvjs_a,gvjs_hq,gvjs_Z)}gvjs_l(gvjs_HQ,gvjs_xK);gvjs_HQ.prototype.jq=function(a,b){return gvjs_wQ(a,b)};function gvjs_IQ(a){gvjs_xK.call(this,a);this.Zd(gvjs_Ps,gvjs_hq,gvjs_Z)}
gvjs_l(gvjs_IQ,gvjs_xK);var gvjs_3ia={jia:gvjs_2e,xha:gvjs_He,Hha:gvjs_Qe,cja:gvjs_8e},gvjs_4ia={fill:gvjs_ho,fillOpacity:.5},gvjs_5ia={chartArea:{top:"0",height:gvjs_zo},enableInteractivity:!1,legend:{position:gvjs_b},hAxis:{textPosition:gvjs_Zs},vAxis:{textPosition:gvjs_b,gridlines:{color:gvjs_b}}},gvjs_6ia={chartArea:{left:"0",width:gvjs_zo},enableInteractivity:!1,legend:{position:gvjs_b},vAxis:{textPosition:gvjs_Zs},hAxis:{textPosition:gvjs_b,gridlines:{color:gvjs_b}}};
function gvjs_JQ(a){gvjs_P.call(this,a);this.Jd={};this.ca=null;this.Hk={Eu:!1};this.EH=this.cK=this.ba=this.C=this.Mg=this.ga=this.Ck=this.R=null;this.aK=50;this.Xba=0;this.KQ=1;this.JV=this.l3=this.pU=!1;this.sQ=this.EQ=this.WX=this.X2=null;this.Uf=!1;this.Jc=null;this.K={range:null,QN:null,vh:null};this.Pj={ml:{min:0,max:0},value:{min:0,max:0}};this.eV=null;this.lW=!1;this.Gu=null}gvjs_l(gvjs_JQ,gvjs_P);gvjs_=gvjs_JQ.prototype;
gvjs_.draw=function(a,b,c){this.Nb();gvjs_jl(a);this.R=a;this.Ck=gvjs_BE(a.Y(0));null==this.cK&&(this.cK=new gvjs_ZJ(gvjs_k(this.Jya,this)));null==this.EH&&(this.EH=new gvjs_ZJ(gvjs_k(this.m4,this,!0)));b=new gvjs_qd([b||{}]);this.pp(b);this.Jc=this.J9(b);c=c||{};if(!this.ca){switch(gvjs_r(b,gvjs_uQ,gvjs_Qe,gvjs_3ia)){case gvjs_He:b=new gvjs_zQ(this.container);break;case gvjs_Qe:b=new gvjs_GK(this.container);break;case gvjs_8e:b=new gvjs_DQ(this.container);break;case gvjs_2e:b=new gvjs_CQ(this.container);
break;default:b=new gvjs_GK(this.container)}this.ca=b;gvjs_0k(this.ca,gvjs_x,gvjs_k(this.cua,this,c))}this.pU&&(this.EQ=this.R.getValue(0,0),this.sQ=this.R.getValue(Math.max(0,this.R.aa()-1),0),b={min:this.EQ,max:this.sQ},c.range&&gvjs_KQ(this,b,c.range),this.Jc.domainAxis=this.Jc.domainAxis||{},this.Jc.domainAxis.viewWindow=b);this.ca.draw(a,this.Jc)};
gvjs_.pp=function(a){this.aK=gvjs_Ed(a,"rangeChangeEventFiringRate",50);this.Xba=gvjs_Ed(a,"minRangeSize",0);this.GX=gvjs_s(a,"fixedRangeSize",!1);this.pU=gvjs_s(a,"zoomAroundSelection",!1);this.l3=gvjs_s(a,"snapToData",!1);this.JV=gvjs_s(a,"centerSelectionAroundData",!1);this.X2=gvjs_5w(a,"sideScreenColor",new gvjs_2(gvjs_4ia));this.WX=new gvjs_2(gvjs_Gw);this.Uf=gvjs_r(a,gvjs_7t,gvjs_Z,gvjs_CF)==gvjs_1};gvjs_.J9=function(a){a=gvjs_Oi(a.nb("chartOptions"));a.theme=this.Uf?gvjs_6ia:gvjs_5ia;return a};
function gvjs_7ia(a,b){var c=gvjs_aE(a.aa(),function(d){return a.getValue(d,0)});c=gvjs_zb(c,function(d){return null!=d});return gvjs_n(c,b)}gvjs_.cua=function(a){gvjs_3k(this.ca);this.Hk={Eu:!0};gvjs_LQ(this,a);gvjs_K(this.C);this.C=this.ca.Sa.$a(1);gvjs_K(this.ba);this.ba=new gvjs_hz;gvjs_8ia(this)};gvjs_.Ica=function(a){gvjs_3k(this.ca);gvjs_LQ(this,a);gvjs_MQ(this,gvjs_sq)};
function gvjs_LQ(a,b){a.ga=a.ca.Yl();a.Mg=a.Uf?a.ga.Vc[0]:a.ga.Gd[0];a.Pj.ml={min:Math.min(a.Mg.bg,a.Mg.rf),max:Math.max(a.Mg.bg,a.Mg.rf)};var c=a.Pj,d=a.Mg.position.zl(a.Mg.bg),e=a.Mg.position.zl(a.Mg.rf);c.value={min:Math.min(d,e),max:Math.max(d,e)};c=a.Xba;if(0>=c)a.KQ=1;else{d=a.Pj.ml.min;e=a.Mg.position.zl(d);if(gvjs_sb(e)){var f=new Date;f.setTime(e.getTime()+c)}else f=e+c;c=Math.ceil(Math.abs(a.Mg.position.uf(f)-d));c=Math.max(c,1);a.KQ=c<a.Pj.ml.max-a.Pj.ml.min?c:1}if(a.l3||a.JV)c=a.Mg,d=
gvjs_7ia(a.R,c.position.uf),c=a.Uf?1==c.Do?d.reverse():d:1==c.Do?d:d.reverse(),a.eV=c;b&&(b=b.range,a.K.range=gvjs_NQ(a,gvjs_i(b)?b.start:null,gvjs_i(b)?b.end:null))}
function gvjs_8ia(a){var b=a.C,c=a.ga,d=b.Zm(c.width,c.height),e=b.Ra(!1);b.appendChild(d,e);d=c.N;b.sb(0,0,c.width,c.height,a.WX,e);c=b.sb(d.left,d.top,d.width,d.height,a.WX,e);var f=gvjs_OQ(a);f=b.sb(f.left,f.top,f.width,f.height,a.X2,e);a.Jd.rangeSelectorMinScreen=f;f=gvjs_PQ(a);f=b.sb(f.left,f.top,f.width,f.height,a.X2,e);a.Jd.rangeSelectorMaxScreen=f;f=gvjs_QQ(a,a.K.range.ci,d,b,e);a.Jd.rangeSelectorMinHandle=f;b=gvjs_QQ(a,a.K.range.bi,d,b,e);a.Jd.rangeSelectorMaxHandle=b;var g=gvjs_Hc(a.container);
a.ba.D(g.body,gvjs_Ig,gvjs_k(a.Gpa,a,a.Hk));a.ba.D(g.body,gvjs_Lg,gvjs_k(a.dP,a,a.Hk));e=e.j();a.ba.D(e,gvjs_Ig,gvjs_k(a.Kqa,a,a.Hk));a.ba.D(e,gvjs_Jg,gvjs_k(a.fI,a,a.Hk,{type:gvjs_Qu,ap:!1}));a.lW=gvjs_4c(e,function(h){return h==g.body});a.lW||a.ba.D(e,gvjs_Lg,gvjs_k(a.dP,a,a.Hk));a.GX||(gvjs_RQ(a,f,gvjs_Jt,gvjs_Jt),gvjs_RQ(a,b,gvjs_At,gvjs_At));a.ba.D(c,gvjs_Fg,gvjs_k(a.CC,a,a.Hk,{vh:gvjs_sq}));a.ba.D(c,gvjs_Kg,gvjs_k(a.fI,a,a.Hk,{type:gvjs_Qu,ap:!0}));a.ba.D(c,gvjs_Jg,gvjs_k(a.fI,a,a.Hk,{type:gvjs_Qu,
ap:!1}));gvjs_M(a,gvjs_x,null)}function gvjs_RQ(a,b,c,d){a.ba.D(b,gvjs_Fg,gvjs_k(a.CC,a,a.Hk,{vh:d}));a.ba.D(b,gvjs_Kg,gvjs_k(a.fI,a,a.Hk,{type:c,ap:!0}));a.ba.D(b,gvjs_Jg,gvjs_k(a.fI,a,a.Hk,{type:c,ap:!1}))}
function gvjs_QQ(a,b,c,d,e){var f=d.Ra(!1);d.appendChild(e,f);e=.5*gvjs_IK.width;var g=.5*gvjs_IK.height,h=a.Uf?c.left:Math.floor(b-e)+.5;b=a.Uf?Math.floor(b-g)+.5:c.top;d.Bp(f.j(),h,b);a.Uf?(b=Math.round(g),b=gvjs_pz(a.Uf?[{x:0,y:b},{x:0+c.width,y:b}]:[{x:0,y:b},{x:0,y:b+c.height}]),d.Ja(b,gvjs_HK,f),a.GX||gvjs_SQ(a,.5*(c.width-gvjs_IK.height),0,gvjs_IK.height,gvjs_IK.width,d,f)):(b=Math.round(e),b=gvjs_pz(a.Uf?[{x:b,y:0},{x:b+c.width,y:0}]:[{x:b,y:0},{x:b,y:0+c.height}]),d.Ja(b,gvjs_HK,f),a.GX||
gvjs_SQ(a,0,.5*(c.height-gvjs_IK.height),gvjs_IK.width,gvjs_IK.height,d,f));return f.j()}function gvjs_SQ(a,b,c,d,e,f,g){d=b+d;e=c+e;var h=gvjs_pz([{x:b+3,y:c},{x:d-3,y:c},{x:d,y:c+3},{x:d,y:e-3},{x:d-3,y:e},{x:b+3,y:e},{x:b,y:e-3},{x:b,y:c+3}],!1);f.Ja(h,gvjs_HK,g);a.Uf?(a=gvjs_pz([{x:b+4,y:c+4},{x:d-4,y:c+4}]),b=gvjs_pz([{x:b+4,y:e-4},{x:d-4,y:e-4}])):(a=gvjs_pz([{x:b+4,y:c+4},{x:b+4,y:e-4}]),b=gvjs_pz([{x:d-4,y:c+4},{x:d-4,y:e-4}]));f.Ja(a,gvjs_HK,g);f.Ja(b,gvjs_HK,g)}
function gvjs_OQ(a){var b=a.ga.N,c=a.K.range.ci;return a.Uf?new gvjs_3(b.left,b.top,b.width,c-b.top):new gvjs_3(b.left,b.top,c-b.left,b.height)}function gvjs_PQ(a){var b=a.ga.N,c=a.K.range.bi;return a.Uf?new gvjs_3(b.left,c,b.width,b.bottom-c):new gvjs_3(c,b.top,b.right-c,b.height)}
function gvjs_NQ(a,b,c){var d=a.Pj.ml.min,e=a.Pj.ml.max,f=1==a.Mg.Do&&!a.Uf;null!=b&&(b=a.Mg.position.uf(b),f?d=Math.max(b,d):e=Math.min(b,e));null!=c&&(a=a.Mg.position.uf(c),f?e=Math.min(a,e):d=Math.max(a,d));return{ci:d,bi:e}}gvjs_.IO=function(){var a=this.K.range,b=this.Mg.position.zl(a.ci);a=this.Mg.position.zl(a.bi);var c=1==this.Mg.Do&&!this.Uf;return{start:c?b:a,end:c?a:b}};
gvjs_.ywa=function(a,b){if(!this.Hk.Eu)return!1;var c=this.K.range;if(null==c.ci||null==c.bi)return!1;a=gvjs_NQ(this,a,b);a=gvjs_TQ(this,a.ci,a.bi,gvjs_sq);this.K.vh=null;return a};function gvjs_TQ(a,b,c,d){var e=a.K.range;if(e.ci==b&&e.bi==c)return!1;a.K.range={ci:b,bi:c};gvjs_MQ(a,d);return!0}
function gvjs_MQ(a,b){var c=a.Uf?gvjs_IK.height:gvjs_IK.width,d=a.Uf?gvjs_IK.width:gvjs_IK.height;if(b!=gvjs_At){var e=gvjs_OQ(a),f=a.Jd.rangeSelectorMinScreen,g=a.Jd.rangeSelectorMinHandle;if(a.Uf){var h=Math.floor(e.top+e.height-.5*d)+.5;a.C.Bp(g,0,h);a.C.jA(f,e.top);a.C.pl(f,e.height)}else h=Math.floor(e.left+e.width-.5*c)+.5,a.C.Bp(g,h,0),a.C.fA(f,e.left),a.C.gh(f,e.width)}b!=gvjs_Jt&&(b=gvjs_PQ(a),e=a.Jd.rangeSelectorMaxScreen,f=a.Jd.rangeSelectorMaxHandle,a.Uf?(h=Math.floor(b.top-.5*d)+.5,a.C.Bp(f,
0,h),a.C.jA(e,b.top),a.C.pl(e,b.height)):(h=Math.floor(b.left-.5*c)+.5,a.C.Bp(f,h,0),a.C.fA(e,b.left),a.C.gh(e,b.width)))}gvjs_.Jya=function(){gvjs_MQ(this,this.K.vh)};function gvjs_UQ(a){var b=a.Pj.ml.max-a.Pj.ml.min,c=a.Mg.Do,d=(a.K.range.ci-a.Pj.ml.min)/b;if(.1>d)return{direction:-1*c,ratio:d/.1};a=(a.Pj.ml.max-a.K.range.bi)/b;return.1>a?{direction:1*c,ratio:a/.1}:null}
function gvjs_VQ(a){if(a.pU){var b=!1;a.K.vh==gvjs_sq&&gvjs_UQ(a)&&(b=!0);b&&!a.Gu?(a.Gu=new gvjs_dz(a.aK),a.ba.D(a.Gu,gvjs_Gv,gvjs_k(a.fpa,a)),a.Gu.start(),gvjs_Xk(a.ca,gvjs_x,gvjs_k(a.Ica,a,null))):!b&&a.Gu&&(gvjs_K(a.Gu),a.Gu=null)}}
gvjs_.fpa=function(){if(this.Gu){var a=gvjs_UQ(this),b=this.aK/gvjs_Vx(1E3,6E4,a.ratio),c=this.Ck.toNumber(this.EQ),d=this.Ck.toNumber(this.sQ),e=(d-c)*b;b=this.Jc.domainAxis.viewWindow;var f=b.max,g=this.Ck.toNumber(b.min);f=this.Ck.toNumber(f);0>a.direction?(a=Math.max(g-e,c),c=f-(g-a)):(c=Math.min(f+e,d),a=g+(c-f));d=this.Ck.zy(a);e=this.Ck.zy(c);if(g!=a||f!=c)b.min=d,b.max=e,this.ca.draw(this.R,this.Jc),this.m4(!0)}};
gvjs_.Kqa=function(a,b){a.Eu&&null!=this.K.vh&&(this.lW||gvjs_WQ(this,b),b.target.style.cursor=gvjs_St)};gvjs_.Gpa=function(a,b){a.Eu&&null!=this.K.vh&&gvjs_WQ(this,b)};
function gvjs_WQ(a,b){var c=a.K;c.range&&null!=c.range.ci&&null!=c.range.bi||(c.range={ci:a.Pj.ml.min,bi:a.Pj.ml.max});b=gvjs_Vy(b);b=(a.Uf?b.y:b.x)-c.QN;var d=a.K.range,e=a.Pj.ml;switch(a.K.vh){case gvjs_sq:var f=e.min-d.ci;var g=e.max-d.bi;break;case gvjs_Jt:f=e.min-d.ci;g=d.bi-a.KQ-d.ci;break;case gvjs_At:f=d.ci+a.KQ-d.bi,g=e.max-d.bi}f=gvjs_Ec(b,f,g);c.QN+=f;c.vh!=gvjs_At&&(c.range.ci+=f);c.vh!=gvjs_Jt&&(c.range.bi+=f);gvjs_VQ(a);gvjs__J(a.cK,a.aK);gvjs__J(a.EH,a.aK)}
gvjs_.CC=function(a,b,c){if(a.Eu&&gvjs_bx(c)){a=gvjs_Vy(c);var d=this.K;d.QN=this.Uf?a.y:a.x;d.vh=b.vh;gvjs_VQ(this);c.preventDefault();c.stopPropagation()}};
gvjs_.dP=function(a){if(a.Eu&&(a=this.K,null!==a.vh)){if(this.l3){var b=this.eV;var c=a.range.bi;var d=gvjs_xQ(b,a.range.ci);c=gvjs_xQ(b,c);gvjs_TQ(this,d,c,a.vh)}else if(this.JV){var e=new gvjs_H(a.range.ci,a.range.bi);d=e.end-e.start;c=this.Pj.ml;var f=b=this.eV,g=gvjs_k(gvjs_Ni,null,e);b=gvjs_ph(f,g);g=gvjs_qx(f,g);if(null===b||null===g)b=gvjs_xQ(f,e.start),f=gvjs_xQ(f,e.end),g=b=f=Math.abs(e.start-b)<=Math.abs(e.end-f)?b:f;e=e.end-e.start;b=gvjs_2x(b,g)-e/2;e=new gvjs_H(b,b+e);e.start=Math.max(e.start,
c.min);e.end=e.start+d;e.end=Math.min(e.end,c.max);e.start=e.end-d;gvjs_TQ(this,e.start,e.end,a.vh)}else this.pU&&a.vh!=gvjs_sq&&(c=this.Jc.domainAxis.viewWindow,d=this.IO(),c=gvjs_KQ(this,c,d))&&(gvjs_Xk(this.ca,gvjs_x,gvjs_k(this.Ica,this,{range:d})),this.ca.draw(this.R,this.Jc));this.m4(!1);a.vh=null;gvjs_VQ(this)}};
function gvjs_KQ(a,b,c){var d=b.max,e=a.Ck.toNumber(b.min);d=a.Ck.toNumber(d);var f=d-e;0===f&&(--e,d+=1,f=2);var g=c.start;c=c.end;if(null==g||null==c)return!1;var h=a.Ck.toNumber(g),k=a.Ck.toNumber(c);c=k-h;g=.1*f;var l=.6*f;if(c>=g&&c<=l)return!1;h=(h+k)/2;f/=(c<g?.9*l:1.1*g)/c;f=new gvjs_H(h-f/2,h+f/2);c<g?gvjs_XQ(f,new gvjs_H(e,d)):(c=a.Ck.toNumber(a.EQ),g=a.Ck.toNumber(a.sQ),gvjs_XQ(f,new gvjs_H(c,g)));c=a.Ck.zy(f.start);a=a.Ck.zy(f.end);e=e!=f.start||d!=f.end;b.min=c;b.max=a;return e}
function gvjs_XQ(a,b){a.start<b.start&&(a.end+=b.start-a.start,a.start=b.start);a.end>b.end&&(a.start-=a.end-b.end,a.end=b.end);a.start<b.start&&(a.start=b.start)}gvjs_.fI=function(a,b,c){a.Eu&&!this.K.vh&&(c.target.style.cursor=b.ap?b.type==gvjs_Qu?gvjs_St:this.Uf?"row-resize":gvjs_vQ:gvjs_xr)};
gvjs_.m4=function(a){var b=this.K.vh,c=this.IO();if(null!=b&&null!=c){var d=this.Mg.Do;gvjs_M(this,gvjs_xu,{start:c.start,end:c.end,startChanged:b==(1==d?gvjs_Jt:gvjs_At)||b==gvjs_sq,endChanged:b==(1==d?gvjs_At:gvjs_Jt)||b==gvjs_sq,inProgress:a})}};gvjs_.Nb=function(){this.ca&&(gvjs_3k(this.ca),gvjs_K(this.cK),this.cK=null,gvjs_K(this.EH),this.EH=null,this.Hk.Eu=!1,gvjs_K(this.C),this.C=null,gvjs_K(this.ba),this.ba=null,this.ca.Nb(),this.ca=null,gvjs_Rk(this),this.Jd={})};gvjs_h(gvjs_Uf,gvjs_xK,void 0);
gvjs_xK.prototype.draw=gvjs_xK.prototype.draw;gvjs_xK.prototype.clearChart=gvjs_xK.prototype.Nb;gvjs_xK.prototype.getImageURI=gvjs_xK.prototype.ij;gvjs_xK.prototype.getSelection=gvjs_xK.prototype.getSelection;gvjs_xK.prototype.setSelection=gvjs_xK.prototype.setSelection;gvjs_xK.prototype.dump=gvjs_xK.prototype.dump;gvjs_xK.prototype.getChartLayoutInterface=gvjs_xK.prototype.Eq;gvjs_xK.prototype.getContainer=gvjs_xK.prototype.getContainer;gvjs_xK.prototype.setAction=gvjs_xK.prototype.zj;
gvjs_xK.prototype.getAction=gvjs_xK.prototype.rh;gvjs_xK.prototype.removeAction=gvjs_xK.prototype.vj;gvjs_h(gvjs_Kf,gvjs_zQ,void 0);gvjs_zQ.prototype.draw=gvjs_zQ.prototype.draw;gvjs_zQ.prototype.clearChart=gvjs_zQ.prototype.Nb;gvjs_zQ.prototype.getImageURI=gvjs_zQ.prototype.ij;gvjs_zQ.prototype.getSelection=gvjs_zQ.prototype.getSelection;gvjs_zQ.prototype.setSelection=gvjs_zQ.prototype.setSelection;gvjs_zQ.prototype.setAction=gvjs_zQ.prototype.zj;gvjs_zQ.prototype.getAction=gvjs_zQ.prototype.rh;
gvjs_zQ.prototype.removeAction=gvjs_zQ.prototype.vj;gvjs_h(gvjs_Lf,gvjs_FQ,void 0);gvjs_FQ.prototype.computeDiff=gvjs_FQ.prototype.jq;gvjs_FQ.prototype.draw=gvjs_FQ.prototype.draw;gvjs_FQ.prototype.clearChart=gvjs_FQ.prototype.Nb;gvjs_FQ.prototype.getImageURI=gvjs_FQ.prototype.ij;gvjs_FQ.prototype.getSelection=gvjs_FQ.prototype.getSelection;gvjs_FQ.prototype.setSelection=gvjs_FQ.prototype.setSelection;gvjs_FQ.prototype.setAction=gvjs_FQ.prototype.zj;gvjs_FQ.prototype.getAction=gvjs_FQ.prototype.rh;
gvjs_FQ.prototype.removeAction=gvjs_FQ.prototype.vj;gvjs_h(gvjs_Mf,gvjs_EQ,void 0);gvjs_EQ.prototype.draw=gvjs_EQ.prototype.draw;gvjs_EQ.prototype.clearChart=gvjs_EQ.prototype.Nb;gvjs_EQ.prototype.getImageURI=gvjs_EQ.prototype.ij;gvjs_EQ.prototype.getSelection=gvjs_EQ.prototype.getSelection;gvjs_EQ.prototype.setSelection=gvjs_EQ.prototype.setSelection;gvjs_EQ.prototype.setAction=gvjs_EQ.prototype.zj;gvjs_EQ.prototype.getAction=gvjs_EQ.prototype.rh;gvjs_EQ.prototype.removeAction=gvjs_EQ.prototype.vj;
gvjs_h(gvjs_Nf,gvjs_GQ,void 0);gvjs_GQ.prototype.draw=gvjs_GQ.prototype.draw;gvjs_GQ.prototype.clearChart=gvjs_GQ.prototype.Nb;gvjs_GQ.prototype.getImageURI=gvjs_GQ.prototype.ij;gvjs_GQ.prototype.getSelection=gvjs_GQ.prototype.getSelection;gvjs_GQ.prototype.setSelection=gvjs_GQ.prototype.setSelection;gvjs_GQ.prototype.setAction=gvjs_GQ.prototype.zj;gvjs_GQ.prototype.getAction=gvjs_GQ.prototype.rh;gvjs_GQ.prototype.removeAction=gvjs_GQ.prototype.vj;gvjs_h(gvjs_2f,gvjs_IQ,void 0);
gvjs_IQ.prototype.draw=gvjs_IQ.prototype.draw;gvjs_IQ.prototype.clearChart=gvjs_IQ.prototype.Nb;gvjs_IQ.prototype.getImageURI=gvjs_IQ.prototype.ij;gvjs_IQ.prototype.getSelection=gvjs_IQ.prototype.getSelection;gvjs_IQ.prototype.setSelection=gvjs_IQ.prototype.setSelection;gvjs_IQ.prototype.setAction=gvjs_IQ.prototype.zj;gvjs_IQ.prototype.getAction=gvjs_IQ.prototype.rh;gvjs_IQ.prototype.removeAction=gvjs_IQ.prototype.vj;gvjs_h(gvjs_Sf,gvjs_HQ,void 0);gvjs_HQ.prototype.computeDiff=gvjs_HQ.prototype.jq;
gvjs_HQ.prototype.draw=gvjs_HQ.prototype.draw;gvjs_HQ.prototype.clearChart=gvjs_HQ.prototype.Nb;gvjs_HQ.prototype.getImageURI=gvjs_HQ.prototype.ij;gvjs_HQ.prototype.getSelection=gvjs_HQ.prototype.getSelection;gvjs_HQ.prototype.setSelection=gvjs_HQ.prototype.setSelection;gvjs_HQ.prototype.setAction=gvjs_HQ.prototype.zj;gvjs_HQ.prototype.getAction=gvjs_HQ.prototype.rh;gvjs_HQ.prototype.removeAction=gvjs_HQ.prototype.vj;gvjs_h(gvjs_Tf,gvjs_GK,void 0);gvjs_GK.prototype.draw=gvjs_GK.prototype.draw;
gvjs_GK.prototype.clearChart=gvjs_GK.prototype.Nb;gvjs_GK.prototype.getImageURI=gvjs_GK.prototype.ij;gvjs_GK.prototype.getSelection=gvjs_GK.prototype.getSelection;gvjs_GK.prototype.setSelection=gvjs_GK.prototype.setSelection;gvjs_GK.prototype.setAction=gvjs_GK.prototype.zj;gvjs_GK.prototype.getAction=gvjs_GK.prototype.rh;gvjs_GK.prototype.removeAction=gvjs_GK.prototype.vj;gvjs_h(gvjs_$f,gvjs_CQ,void 0);gvjs_CQ.prototype.draw=gvjs_CQ.prototype.draw;gvjs_CQ.prototype.clearChart=gvjs_CQ.prototype.Nb;
gvjs_CQ.prototype.getImageURI=gvjs_CQ.prototype.ij;gvjs_CQ.prototype.getSelection=gvjs_CQ.prototype.getSelection;gvjs_CQ.prototype.setSelection=gvjs_CQ.prototype.setSelection;gvjs_CQ.prototype.setAction=gvjs_CQ.prototype.zj;gvjs_CQ.prototype.getAction=gvjs_CQ.prototype.rh;gvjs_CQ.prototype.removeAction=gvjs_CQ.prototype.vj;gvjs_h(gvjs_fg,gvjs_yK,void 0);gvjs_yK.prototype.computeDiff=gvjs_yK.prototype.jq;gvjs_yK.prototype.draw=gvjs_yK.prototype.draw;gvjs_yK.prototype.clearChart=gvjs_yK.prototype.Nb;
gvjs_yK.prototype.getImageURI=gvjs_yK.prototype.ij;gvjs_yK.prototype.getSelection=gvjs_yK.prototype.getSelection;gvjs_yK.prototype.setSelection=gvjs_yK.prototype.setSelection;gvjs_yK.prototype.setAction=gvjs_yK.prototype.zj;gvjs_yK.prototype.getAction=gvjs_yK.prototype.rh;gvjs_yK.prototype.removeAction=gvjs_yK.prototype.vj;gvjs_h(gvjs_ig,gvjs_DQ,void 0);gvjs_DQ.prototype.computeDiff=gvjs_DQ.prototype.jq;gvjs_DQ.prototype.draw=gvjs_DQ.prototype.draw;gvjs_DQ.prototype.clearChart=gvjs_DQ.prototype.Nb;
gvjs_DQ.prototype.getImageURI=gvjs_DQ.prototype.ij;gvjs_DQ.prototype.getSelection=gvjs_DQ.prototype.getSelection;gvjs_DQ.prototype.setSelection=gvjs_DQ.prototype.setSelection;gvjs_DQ.prototype.setAction=gvjs_DQ.prototype.zj;gvjs_DQ.prototype.getAction=gvjs_DQ.prototype.rh;gvjs_DQ.prototype.removeAction=gvjs_DQ.prototype.vj;gvjs_h(gvjs_jg,gvjs_BQ,void 0);gvjs_BQ.prototype.draw=gvjs_BQ.prototype.draw;gvjs_BQ.prototype.clearChart=gvjs_BQ.prototype.Nb;gvjs_BQ.prototype.getImageURI=gvjs_BQ.prototype.ij;
gvjs_BQ.prototype.getSelection=gvjs_BQ.prototype.getSelection;gvjs_BQ.prototype.setSelection=gvjs_BQ.prototype.setSelection;gvjs_BQ.prototype.setAction=gvjs_BQ.prototype.zj;gvjs_BQ.prototype.getAction=gvjs_BQ.prototype.rh;gvjs_BQ.prototype.removeAction=gvjs_BQ.prototype.vj;gvjs_h(gvjs_kg,gvjs_AQ,void 0);gvjs_AQ.prototype.draw=gvjs_AQ.prototype.draw;gvjs_AQ.prototype.clearChart=gvjs_AQ.prototype.Nb;gvjs_AQ.prototype.getImageURI=gvjs_AQ.prototype.ij;gvjs_AQ.prototype.getSelection=gvjs_AQ.prototype.getSelection;
gvjs_AQ.prototype.setSelection=gvjs_AQ.prototype.setSelection;gvjs_AQ.prototype.setAction=gvjs_AQ.prototype.zj;gvjs_AQ.prototype.getAction=gvjs_AQ.prototype.rh;gvjs_AQ.prototype.removeAction=gvjs_AQ.prototype.vj;gvjs_h("google.visualization.RangeSelector",gvjs_JQ,void 0);gvjs_JQ.prototype.draw=gvjs_JQ.prototype.draw;gvjs_JQ.prototype.clearChart=gvjs_JQ.prototype.Nb;gvjs_JQ.prototype.getRange=gvjs_JQ.prototype.IO;gvjs_JQ.prototype.setRange=gvjs_JQ.prototype.ywa;/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
gvjs_Li(gvjs_v);function gvjs_YQ(a){return(new gvjs_6j).sd().sanitize(a)};
