/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var gvjs_aa="#000000",gvjs_ba="#808080",gvjs_ca="#ffffff",gvjs_da=", ",gvjs_ea="0000000000000000",gvjs_fa="<br>",gvjs_ga="April",gvjs_ha="August",gvjs_ia="Can't combine significant digits and minimum fraction digits",gvjs_ja="December",gvjs_ka="Edge",gvjs_la="February",gvjs_ma="Friday",gvjs_na="IFRAME",gvjs_oa="INPUT",gvjs_pa="Inconsistent use of percent/permill characters",gvjs_qa="January",gvjs_ra="Map",gvjs_sa="March",gvjs_ta="May",gvjs_ua="Monday",gvjs_va="November",gvjs_wa="OBJECT",gvjs_xa="October",
gvjs_ya="SOURCE",gvjs_za="STYLE",gvjs_Aa="Saturday",gvjs_Ba="September",gvjs_Ca="Sunday",gvjs_Da="Thursday",gvjs_Ea="Too many percent/permill",gvjs_Fa="Tuesday",gvjs_Ga="Wednesday",gvjs_Ha="_bar_format_old_value",gvjs_Ia="array",gvjs_Ja="background-color:",gvjs_Ka="boolean",gvjs_La="class",gvjs_Ma="className",gvjs_Na="color:",gvjs_Oa="date",gvjs_Pa="datetime",gvjs_Qa="div",gvjs_Ra="false",gvjs_Sa="full",gvjs_a="function",gvjs_Ta="google.visualization.NumberFormat",gvjs_Ua="height",gvjs_Va="medium",
gvjs_b="none",gvjs_Wa="null",gvjs_c="number",gvjs_d="object",gvjs_Xa="pattern",gvjs_Ya="prefix",gvjs_Za="role",gvjs__a="short",gvjs_e="string",gvjs_0a="style",gvjs_1a="suffix",gvjs_2a="timeofday",gvjs_3a="transparent",gvjs_4a="true",gvjs_5a="type",gvjs_6a="width",gvjs_7a="{1} 'at' {0}",gvjs_8a="{1}, {0}",gvjs_,gvjs_9a=[];function gvjs_f(a){return function(){return gvjs_9a[a].apply(this,arguments)}}function gvjs_$a(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}
function gvjs_ab(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):{next:gvjs_$a(a)}}var gvjs_aaa=typeof Object.create==gvjs_a?Object.create:function(a){function b(){}b.prototype=a;return new b},gvjs_bb;
if(typeof Object.setPrototypeOf==gvjs_a)gvjs_bb=Object.setPrototypeOf;else{var gvjs_cb;a:{var gvjs_baa={a:!0},gvjs_db={};try{gvjs_db.__proto__=gvjs_baa;gvjs_cb=gvjs_db.a;break a}catch(a){}gvjs_cb=!1}gvjs_bb=gvjs_cb?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var gvjs_eb=gvjs_bb,gvjs_fb=typeof Object.defineProperties==gvjs_a?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};
function gvjs_caa(a){a=[gvjs_d==typeof globalThis&&globalThis,a,gvjs_d==typeof window&&window,gvjs_d==typeof self&&self,gvjs_d==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");}var gvjs_gb=gvjs_caa(this);
function gvjs_hb(a,b){if(b){var c=gvjs_gb;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];e in c||(c[e]={});c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&gvjs_fb(c,a,{configurable:!0,writable:!0,value:b})}}
gvjs_hb("Symbol",function(a){function b(e){if(this instanceof b)throw new TypeError("Symbol is not a constructor");return new c("jscomp_symbol_"+(e||"")+"_"+d++,e)}function c(e,f){this.pha=e;gvjs_fb(this,"description",{configurable:!0,writable:!0,value:f})}if(a)return a;c.prototype.toString=function(){return this.pha};var d=0;return b});
function gvjs_ib(){gvjs_ib=function(){};var a=Symbol.iterator;a||(a=Symbol.iterator=Symbol("Symbol.iterator"));typeof Array.prototype[a]!=gvjs_a&&gvjs_fb(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return gvjs_jb(gvjs_$a(this))}})}function gvjs_jb(a){gvjs_ib();a={next:a};a[Symbol.iterator]=function(){return this};return a}
function gvjs_kb(a,b,c){a instanceof String&&(a=String(a));for(var d=a.length,e=0;e<d;e++){var f=a[e];if(b.call(c,f,e,a))return{yb:e,v:f}}return{yb:-1,v:void 0}}gvjs_hb("Array.prototype.findIndex",function(a){return a?a:function(b,c){return gvjs_kb(this,b,c).yb}});
function gvjs_lb(a,b,c){if(null==a)throw new TypeError("The 'this' value for String.prototype."+c+" must not be null or undefined");if(b instanceof RegExp)throw new TypeError("First argument to String.prototype."+c+" must not be a regular expression");return a+""}
gvjs_hb("String.prototype.endsWith",function(a){return a?a:function(b,c){var d=gvjs_lb(this,b,"endsWith");b+="";void 0===c&&(c=d.length);c=Math.max(0,Math.min(c|0,d.length));for(var e=b.length;0<e&&0<c;)if(d[--c]!=b[--e])return!1;return 0>=e}});gvjs_hb("Array.prototype.find",function(a){return a?a:function(b,c){return gvjs_kb(this,b,c).v}});
gvjs_hb("String.prototype.startsWith",function(a){return a?a:function(b,c){var d=gvjs_lb(this,b,"startsWith");b+="";var e=d.length,f=b.length;c=Math.max(0,Math.min(c|0,d.length));for(var g=0;g<f&&c<e;)if(d[c++]!=b[g++])return!1;return g>=f}});gvjs_hb("String.prototype.repeat",function(a){return a?a:function(b){var c=gvjs_lb(this,null,"repeat");if(0>b||1342177279<b)throw new RangeError("Invalid count value");b|=0;for(var d="";b;)if(b&1&&(d+=c),b>>>=1)c+=c;return d}});
function gvjs_mb(a,b){return Object.prototype.hasOwnProperty.call(a,b)}var gvjs_daa=typeof Object.assign==gvjs_a?Object.assign:function(a,b){for(var c=1;c<arguments.length;c++){var d=arguments[c];if(d)for(var e in d)gvjs_mb(d,e)&&(a[e]=d[e])}return a};gvjs_hb("Object.assign",function(a){return a||gvjs_daa});
gvjs_hb("Promise",function(a){function b(g){this.K=0;this.wm=void 0;this.JD=[];var h=this.yW();try{g(h.resolve,h.reject)}catch(k){h.reject(k)}}function c(){this.Iu=null}function d(g){return g instanceof b?g:new b(function(h){h(g)})}if(a)return a;c.prototype.p6=function(g){if(null==this.Iu){this.Iu=[];var h=this;this.q6(function(){h.Fna()})}this.Iu.push(g)};var e=gvjs_gb.setTimeout;c.prototype.q6=function(g){e(g,0)};c.prototype.Fna=function(){for(;this.Iu&&this.Iu.length;){var g=this.Iu;this.Iu=[];
for(var h=0;h<g.length;++h){var k=g[h];g[h]=null;try{k()}catch(l){this.hka(l)}}}this.Iu=null};c.prototype.hka=function(g){this.q6(function(){throw g;})};b.prototype.yW=function(){function g(l){return function(m){k||(k=!0,l.call(h,m))}}var h=this,k=!1;return{resolve:g(this.Gva),reject:g(this.E1)}};b.prototype.Gva=function(g){if(g===this)this.E1(new TypeError("A Promise cannot resolve to itself"));else if(g instanceof b)this.Hwa(g);else{a:switch(typeof g){case gvjs_d:var h=null!=g;break a;case gvjs_a:h=
!0;break a;default:h=!1}h?this.Fva(g):this.B9(g)}};b.prototype.Fva=function(g){var h=void 0;try{h=g.then}catch(k){this.E1(k);return}typeof h==gvjs_a?this.Iwa(h,g):this.B9(g)};b.prototype.E1=function(g){this.ffa(2,g)};b.prototype.B9=function(g){this.ffa(1,g)};b.prototype.ffa=function(g,h){if(0!=this.K)throw Error("Cannot settle("+g+gvjs_da+h+"): Promise already settled in state"+this.K);this.K=g;this.wm=h;this.Hna()};b.prototype.Hna=function(){if(null!=this.JD){for(var g=0;g<this.JD.length;++g)f.p6(this.JD[g]);
this.JD=null}};var f=new c;b.prototype.Hwa=function(g){var h=this.yW();g.JM(h.resolve,h.reject)};b.prototype.Iwa=function(g,h){var k=this.yW();try{g.call(h,k.resolve,k.reject)}catch(l){k.reject(l)}};b.prototype.then=function(g,h){function k(p,q){return typeof p==gvjs_a?function(r){try{l(p(r))}catch(t){m(t)}}:q}var l,m,n=new b(function(p,q){l=p;m=q});this.JM(k(g,l),k(h,m));return n};b.prototype.catch=function(g){return this.then(void 0,g)};b.prototype.JM=function(g,h){function k(){switch(l.K){case 1:g(l.wm);
break;case 2:h(l.wm);break;default:throw Error("Unexpected state: "+l.K);}}var l=this;null==this.JD?f.p6(k):this.JD.push(k)};b.resolve=d;b.reject=function(g){return new b(function(h,k){k(g)})};b.race=function(g){return new b(function(h,k){for(var l=gvjs_ab(g),m=l.next();!m.done;m=l.next())d(m.value).JM(h,k)})};b.all=function(g){var h=gvjs_ab(g),k=h.next();return k.done?d([]):new b(function(l,m){function n(r){return function(t){p[r]=t;q--;0==q&&l(p)}}var p=[],q=0;do p.push(void 0),q++,d(k.value).JM(n(p.length-
1),m),k=h.next();while(!k.done)})};return b});gvjs_hb("Array.from",function(a){return a?a:function(b,c,d){c=null!=c?c:function(h){return h};var e=[],f="undefined"!=typeof Symbol&&Symbol.iterator&&b[Symbol.iterator];if(typeof f==gvjs_a){b=f.call(b);for(var g=0;!(f=b.next()).done;)e.push(c.call(d,f.value,g++))}else for(f=b.length,g=0;g<f;g++)e.push(c.call(d,b[g],g));return e}});
gvjs_hb("Array.prototype.fill",function(a){return a?a:function(b,c,d){var e=this.length||0;0>c&&(c=Math.max(0,e+c));if(null==d||d>e)d=e;d=Number(d);0>d&&(d=Math.max(0,e+d));for(c=Number(c||0);c<d;c++)this[c]=b;return this}});function gvjs_nb(a,b){gvjs_ib();a instanceof String&&(a+="");var c=0,d={next:function(){if(c<a.length){var e=c++;return{value:b(e,a[e]),done:!1}}d.next=function(){return{done:!0,value:void 0}};return d.next()}};d[Symbol.iterator]=function(){return d};return d}
gvjs_hb("Array.prototype.keys",function(a){return a?a:function(){return gvjs_nb(this,function(b){return b})}});
gvjs_hb("WeakMap",function(a){function b(k){this.dc=(h+=Math.random()+1).toString();if(k){k=gvjs_ab(k);for(var l;!(l=k.next()).done;)l=l.value,this.set(l[0],l[1])}}function c(){}function d(k){var l=typeof k;return l===gvjs_d&&null!==k||l===gvjs_a}function e(k){if(!gvjs_mb(k,g)){var l=new c;gvjs_fb(k,g,{value:l})}}function f(k){var l=Object[k];l&&(Object[k]=function(m){if(m instanceof c)return m;e(m);return l(m)})}if(function(){if(!a||!Object.seal)return!1;try{var k=Object.seal({}),l=Object.seal({}),
m=new a([[k,2],[l,3]]);if(2!=m.get(k)||3!=m.get(l))return!1;m.delete(k);m.set(l,4);return!m.has(k)&&4==m.get(l)}catch(n){return!1}}())return a;var g="$jscomp_hidden_"+Math.random();f("freeze");f("preventExtensions");f("seal");var h=0;b.prototype.set=function(k,l){if(!d(k))throw Error("Invalid WeakMap key");e(k);if(!gvjs_mb(k,g))throw Error("WeakMap key fail: "+k);k[g][this.dc]=l;return this};b.prototype.get=function(k){return d(k)&&gvjs_mb(k,g)?k[g][this.dc]:void 0};b.prototype.has=function(k){return d(k)&&
gvjs_mb(k,g)&&gvjs_mb(k[g],this.dc)};b.prototype.delete=function(k){return d(k)&&gvjs_mb(k,g)&&gvjs_mb(k[g],this.dc)?delete k[g][this.dc]:!1};return b});gvjs_hb("Object.values",function(a){return a?a:function(b){var c=[],d;for(d in b)gvjs_mb(b,d)&&c.push(b[d]);return c}});gvjs_hb("Object.is",function(a){return a?a:function(b,c){return b===c?0!==b||1/b===1/c:b!==b&&c!==c}});
gvjs_hb("Array.prototype.includes",function(a){return a?a:function(b,c){var d=this;d instanceof String&&(d=String(d));var e=d.length;c=c||0;for(0>c&&(c=Math.max(c+e,0));c<e;c++){var f=d[c];if(f===b||Object.is(f,b))return!0}return!1}});
gvjs_hb(gvjs_ra,function(a){function b(){var h={};return h.ue=h.next=h.head=h}function c(h,k){var l=h.Ac;return gvjs_jb(function(){if(l){for(;l.head!=h.Ac;)l=l.ue;for(;l.next!=l.head;)return l=l.next,{done:!1,value:k(l)};l=null}return{done:!0,value:void 0}})}function d(h,k){var l=k&&typeof k;l==gvjs_d||l==gvjs_a?f.has(k)?l=f.get(k):(l=""+ ++g,f.set(k,l)):l="p_"+k;var m=h.qa[l];if(m&&gvjs_mb(h.qa,l))for(h=0;h<m.length;h++){var n=m[h];if(k!==k&&n.key!==n.key||k===n.key)return{id:l,list:m,index:h,ad:n}}return{id:l,
list:m,index:-1,ad:void 0}}function e(h){this.qa={};this.Ac=b();this.size=0;if(h){h=gvjs_ab(h);for(var k;!(k=h.next()).done;)k=k.value,this.set(k[0],k[1])}}if(function(){if(!a||typeof a!=gvjs_a||!a.prototype.entries||typeof Object.seal!=gvjs_a)return!1;try{var h=Object.seal({x:4}),k=new a(gvjs_ab([[h,"s"]]));if("s"!=k.get(h)||1!=k.size||k.get({x:4})||k.set({x:4},"t")!=k||2!=k.size)return!1;var l=k.entries(),m=l.next();if(m.done||m.value[0]!=h||"s"!=m.value[1])return!1;m=l.next();return m.done||4!=
m.value[0].x||"t"!=m.value[1]||!l.next().done?!1:!0}catch(n){return!1}}())return a;gvjs_ib();var f=new WeakMap;e.prototype.set=function(h,k){h=0===h?0:h;var l=d(this,h);l.list||(l.list=this.qa[l.id]=[]);l.ad?l.ad.value=k:(l.ad={next:this.Ac,ue:this.Ac.ue,head:this.Ac,key:h,value:k},l.list.push(l.ad),this.Ac.ue.next=l.ad,this.Ac.ue=l.ad,this.size++);return this};e.prototype.delete=function(h){h=d(this,h);return h.ad&&h.list?(h.list.splice(h.index,1),h.list.length||delete this.qa[h.id],h.ad.ue.next=
h.ad.next,h.ad.next.ue=h.ad.ue,h.ad.head=null,this.size--,!0):!1};e.prototype.clear=function(){this.qa={};this.Ac=this.Ac.ue=b();this.size=0};e.prototype.has=function(h){return!!d(this,h).ad};e.prototype.get=function(h){return(h=d(this,h).ad)&&h.value};e.prototype.entries=function(){return c(this,function(h){return[h.key,h.value]})};e.prototype.keys=function(){return c(this,function(h){return h.key})};e.prototype.values=function(){return c(this,function(h){return h.value})};e.prototype.forEach=function(h,
k){for(var l=this.entries(),m;!(m=l.next()).done;)m=m.value,h.call(k,m[1],m[0],this)};e.prototype[Symbol.iterator]=e.prototype.entries;var g=0;return e});gvjs_hb("Array.prototype.values",function(a){return a?a:function(){return gvjs_nb(this,function(b,c){return c})}});gvjs_hb("Object.entries",function(a){return a?a:function(b){var c=[],d;for(d in b)gvjs_mb(b,d)&&c.push([d,b[d]]);return c}});
gvjs_hb("Array.prototype.entries",function(a){return a?a:function(){return gvjs_nb(this,function(b,c){return[b,c]})}});gvjs_hb("Math.log10",function(a){return a?a:function(b){return Math.log(b)/Math.LN10}});gvjs_hb("Number.isFinite",function(a){return a?a:function(b){return typeof b!==gvjs_c?!1:!isNaN(b)&&Infinity!==b&&-Infinity!==b}});gvjs_hb("Number.isInteger",function(a){return a?a:function(b){return Number.isFinite(b)?b===Math.floor(b):!1}});
gvjs_hb("Math.cbrt",function(a){return a?a:function(b){if(0===b)return b;b=Number(b);var c=Math.pow(Math.abs(b),1/3);return 0>b?-c:c}});gvjs_hb("Math.log2",function(a){return a?a:function(b){return Math.log(b)/Math.LN2}});
gvjs_hb("Set",function(a){function b(c){this.ta=new Map;if(c){c=gvjs_ab(c);for(var d;!(d=c.next()).done;)this.add(d.value)}this.size=this.ta.size}if(function(){if(!a||typeof a!=gvjs_a||!a.prototype.entries||typeof Object.seal!=gvjs_a)return!1;try{var c=Object.seal({x:4}),d=new a(gvjs_ab([c]));if(!d.has(c)||1!=d.size||d.add(c)!=d||1!=d.size||d.add({x:4})!=d||2!=d.size)return!1;var e=d.entries(),f=e.next();if(f.done||f.value[0]!=c||f.value[1]!=c)return!1;f=e.next();return f.done||f.value[0]==c||4!=
f.value[0].x||f.value[1]!=f.value[0]?!1:e.next().done}catch(g){return!1}}())return a;gvjs_ib();b.prototype.add=function(c){c=0===c?0:c;this.ta.set(c,c);this.size=this.ta.size;return this};b.prototype.delete=function(c){c=this.ta.delete(c);this.size=this.ta.size;return c};b.prototype.clear=function(){this.ta.clear();this.size=0};b.prototype.has=function(c){return this.ta.has(c)};b.prototype.entries=function(){return this.ta.entries()};b.prototype.values=function(){return this.ta.values()};b.prototype.keys=
b.prototype.values;b.prototype[Symbol.iterator]=b.prototype.values;b.prototype.forEach=function(c,d){var e=this;this.ta.forEach(function(f){return c.call(d,f,f,e)})};return b});var gvjs_ob=gvjs_ob||{},gvjs_g=this||self;function gvjs_h(a,b,c){a=a.split(".");c=c||gvjs_g;a[0]in c||"undefined"==typeof c.execScript||c.execScript("var "+a[0]);for(var d;a.length&&(d=a.shift());)a.length||void 0===b?c=c[d]&&c[d]!==Object.prototype[d]?c[d]:c[d]={}:c[d]=b}function gvjs_pb(){}
function gvjs_qb(a){var b=typeof a;if(b==gvjs_d)if(a){if(a instanceof Array)return gvjs_Ia;if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return gvjs_d;if("[object Array]"==c||typeof a.length==gvjs_c&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return gvjs_Ia;if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return gvjs_a}else return gvjs_Wa;
else if(b==gvjs_a&&"undefined"==typeof a.call)return gvjs_d;return b}function gvjs_rb(a){var b=gvjs_qb(a);return b==gvjs_Ia||b==gvjs_d&&typeof a.length==gvjs_c}function gvjs_sb(a){return gvjs_i(a)&&typeof a.getFullYear==gvjs_a}function gvjs_j(a){return gvjs_qb(a)==gvjs_a}function gvjs_i(a){var b=typeof a;return b==gvjs_d&&null!=a||b==gvjs_a}var gvjs_tb="closure_uid_"+(1E9*Math.random()>>>0);function gvjs_eaa(a,b,c){return a.call.apply(a.bind,arguments)}
function gvjs_faa(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var e=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(e,d);return a.apply(b,e)}}return function(){return a.apply(b,arguments)}}function gvjs_k(a,b,c){gvjs_k=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?gvjs_eaa:gvjs_faa;return gvjs_k.apply(null,arguments)}
function gvjs_ub(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var d=c.slice();d.push.apply(d,arguments);return a.apply(this,d)}}var gvjs_vb=Date.now||function(){return+new Date};function gvjs_l(a,b){function c(){}c.prototype=b.prototype;a.o=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.base=function(d,e,f){for(var g=Array(arguments.length-2),h=2;h<arguments.length;h++)g[h-2]=arguments[h];return b.prototype[e].apply(d,g)}};var google=google||window.google||{};var gvjs_wb;var gvjs_xb=Array.prototype.indexOf?function(a,b){return Array.prototype.indexOf.call(a,b,void 0)}:function(a,b){if(typeof a===gvjs_e)return typeof b!==gvjs_e||1!=b.length?-1:a.indexOf(b,0);for(var c=0;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},gvjs_gaa=Array.prototype.lastIndexOf?function(a,b){return Array.prototype.lastIndexOf.call(a,b,a.length-1)}:function(a,b){var c=a.length-1;0>c&&(c=Math.max(0,a.length+c));if(typeof a===gvjs_e)return typeof b!==gvjs_e||1!=b.length?-1:a.lastIndexOf(b,
c);for(;0<=c;c--)if(c in a&&a[c]===b)return c;return-1},gvjs_m=Array.prototype.forEach?function(a,b,c){Array.prototype.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=typeof a===gvjs_e?a.split(""):a,f=0;f<d;f++)f in e&&b.call(c,e[f],f,a)};function gvjs_yb(a,b){for(var c=typeof a===gvjs_e?a.split(""):a,d=a.length-1;0<=d;--d)d in c&&b.call(void 0,c[d],d,a)}
var gvjs_zb=Array.prototype.filter?function(a,b,c){return Array.prototype.filter.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=[],f=0,g=typeof a===gvjs_e?a.split(""):a,h=0;h<d;h++)if(h in g){var k=g[h];b.call(c,k,h,a)&&(e[f++]=k)}return e},gvjs_n=Array.prototype.map?function(a,b,c){return Array.prototype.map.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=Array(d),f=typeof a===gvjs_e?a.split(""):a,g=0;g<d;g++)g in f&&(e[g]=b.call(c,f[g],g,a));return e},gvjs_Ab=Array.prototype.reduce?function(a,
b,c,d){d&&(b=gvjs_k(b,d));return Array.prototype.reduce.call(a,b,c)}:function(a,b,c,d){var e=c;gvjs_m(a,function(f,g){e=b.call(d,e,f,g,a)});return e},gvjs_haa=Array.prototype.reduceRight?function(a,b,c){return Array.prototype.reduceRight.call(a,b,c)}:function(a,b,c){var d=c;gvjs_yb(a,function(e,f){d=b.call(void 0,d,e,f,a)});return d},gvjs_Bb=Array.prototype.some?function(a,b,c){return Array.prototype.some.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=typeof a===gvjs_e?a.split(""):a,f=0;f<d;f++)if(f in
e&&b.call(c,e[f],f,a))return!0;return!1},gvjs_Cb=Array.prototype.every?function(a,b,c){return Array.prototype.every.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=typeof a===gvjs_e?a.split(""):a,f=0;f<d;f++)if(f in e&&!b.call(c,e[f],f,a))return!1;return!0};function gvjs_Db(a,b){return 0<=gvjs_xb(a,b)}function gvjs_Eb(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]}function gvjs_Fb(a,b){for(var c=[],d=0;d<b;d++)c[d]=a;return c};function gvjs_Gb(a,b){return(new gvjs_Hb(b)).ne(a)}function gvjs_Hb(a){this.PR=a}gvjs_Hb.prototype.ne=function(a){var b=[];gvjs_Ib(this,a,b);return b.join("")};
function gvjs_Ib(a,b,c){if(null==b)c.push(gvjs_Wa);else{if(typeof b==gvjs_d){if(Array.isArray(b)){var d=b;b=d.length;c.push("[");for(var e="",f=0;f<b;f++)c.push(e),e=d[f],gvjs_Ib(a,a.PR?a.PR.call(d,String(f),e):e,c),e=",";c.push("]");return}if(b instanceof String||b instanceof Number||b instanceof Boolean)b=b.valueOf();else{c.push("{");f="";for(d in b)Object.prototype.hasOwnProperty.call(b,d)&&(e=b[d],typeof e!=gvjs_a&&(c.push(f),gvjs_Jb(d,c),c.push(":"),gvjs_Ib(a,a.PR?a.PR.call(b,d,e):e,c),f=","));
c.push("}");return}}switch(typeof b){case gvjs_e:gvjs_Jb(b,c);break;case gvjs_c:c.push(isFinite(b)&&!isNaN(b)?String(b):gvjs_Wa);break;case gvjs_Ka:c.push(String(b));break;case gvjs_a:c.push(gvjs_Wa);break;default:throw Error("Unknown type: "+typeof b);}}}var gvjs_Kb={'"':'\\"',"\\":"\\\\","/":"\\/","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\u000b"},gvjs_iaa=/\uffff/.test("\uffff")?/[\\"\x00-\x1f\x7f-\uffff]/g:/[\\"\x00-\x1f\x7f-\xff]/g;
function gvjs_Jb(a,b){b.push('"',a.replace(gvjs_iaa,function(c){var d=gvjs_Kb[c];d||(d="\\u"+(c.charCodeAt(0)|65536).toString(16).substr(1),gvjs_Kb[c]=d);return d}),'"')};function gvjs_Lb(a){var b=!1,c;return function(){b||(c=a(),b=!0);return c}};function gvjs_o(a,b,c){for(var d in a)b.call(c,a[d],d,a)}function gvjs_Mb(a,b){for(var c in a)if(a[c]==b)return!0;return!1}function gvjs_p(a){var b={},c;for(c in a)b[c]=a[c];return b};function gvjs_Nb(){this.m1="";this.Yia=gvjs_Ob}gvjs_Nb.prototype.Zo=!0;var gvjs_Ob={};gvjs_Nb.prototype.cl=function(){return this.m1.toString()};gvjs_Nb.prototype.fl=function(a){this.m1=a;return this};var gvjs_jaa=(new gvjs_Nb).fl("");function gvjs_Pb(a,b){return 0==a.lastIndexOf(b,0)}function gvjs_Qb(a){var b=a.length-1;return 0<=b&&a.indexOf("%",b)==b}function gvjs_Rb(a){return/^[\s\xa0]*$/.test(a)}var gvjs_Sb=String.prototype.trim?function(a){return a.trim()}:function(a){return/^[\s\xa0]*([\s\S]*?)[\s\xa0]*$/.exec(a)[1]};function gvjs_Tb(a,b){return-1!=a.indexOf(b)}
function gvjs_Ub(a,b){var c=0;a=gvjs_Sb(String(a)).split(".");b=gvjs_Sb(String(b)).split(".");for(var d=Math.max(a.length,b.length),e=0;0==c&&e<d;e++){var f=a[e]||"",g=b[e]||"";do{f=/(\d*)(\D*)(.*)/.exec(f)||["","","",""];g=/(\d*)(\D*)(.*)/.exec(g)||["","","",""];if(0==f[0].length&&0==g[0].length)break;c=gvjs_Vb(0==f[1].length?0:parseInt(f[1],10),0==g[1].length?0:parseInt(g[1],10))||gvjs_Vb(0==f[2].length,0==g[2].length)||gvjs_Vb(f[2],g[2]);f=f[3];g=g[3]}while(0==c)}return c}
function gvjs_Vb(a,b){return a<b?-1:a>b?1:0};function gvjs_Wb(){this.o1="";this.$ia=gvjs_Xb}gvjs_Wb.prototype.Zo=!0;var gvjs_Xb={};gvjs_Wb.prototype.cl=function(){return this.o1};gvjs_Wb.prototype.fl=function(a){this.o1=a;return this};var gvjs_Yb=(new gvjs_Wb).fl("");function gvjs_Zb(){this.n1="";this.Zia=gvjs__b}gvjs_Zb.prototype.Zo=!0;var gvjs__b={};gvjs_Zb.prototype.cl=function(){return this.n1};gvjs_Zb.prototype.fl=function(a){this.n1=a;return this};var gvjs_0b=(new gvjs_Zb).fl("");var gvjs_1b;a:{var gvjs_2b=gvjs_g.navigator;if(gvjs_2b){var gvjs_3b=gvjs_2b.userAgent;if(gvjs_3b){gvjs_1b=gvjs_3b;break a}}gvjs_1b=""}function gvjs_4b(a){return gvjs_Tb(gvjs_1b,a)};function gvjs_5b(){this.wR="";this.Xia=gvjs_6b;this.ZW=null}gvjs_5b.prototype.sZ=!0;gvjs_5b.prototype.tn=gvjs_f(2);gvjs_5b.prototype.Zo=!0;gvjs_5b.prototype.cl=function(){return this.wR.toString()};function gvjs_7b(a){if(a instanceof gvjs_5b&&a.constructor===gvjs_5b&&a.Xia===gvjs_6b)return a.wR;gvjs_qb(a);return"type_error:SafeHtml"}var gvjs_6b={};function gvjs_8b(a,b){return(new gvjs_5b).fl(a,b)}gvjs_5b.prototype.fl=function(a,b){this.wR=a;this.ZW=b;return this};var gvjs_9b=new gvjs_5b;
gvjs_9b.wR=gvjs_g.trustedTypes&&gvjs_g.trustedTypes.emptyHTML?gvjs_g.trustedTypes.emptyHTML:"";gvjs_9b.ZW=0;var gvjs_$b=gvjs_9b,gvjs_ac=gvjs_8b(gvjs_fa,0);var gvjs_kaa=gvjs_Lb(function(){var a=document.createElement(gvjs_Qa),b=document.createElement(gvjs_Qa);b.appendChild(document.createElement(gvjs_Qa));a.appendChild(b);b=a.firstChild.firstChild;a.innerHTML=gvjs_7b(gvjs_$b);return!b.parentElement});var gvjs_bc=String.prototype.repeat?function(a,b){return a.repeat(b)}:function(a,b){return Array(b+1).join(a)};function gvjs_cc(a,b){a=String(a);var c=a.indexOf(".");-1==c&&(c=a.length);return gvjs_bc("0",Math.max(0,b-c))+a}function gvjs_dc(a){return null==a?"":String(a)}var gvjs_ec=2147483648*Math.random()|0;function gvjs_fc(a){var b=Number(a);return 0==b&&gvjs_Rb(a)?NaN:b};var gvjs_gc=JSON.parse,gvjs_hc=gvjs_g.JSON&&gvjs_g.JSON.stringify||gvjs_Gb;function gvjs_ic(){return gvjs_4b("iPhone")&&!gvjs_4b("iPod")&&!gvjs_4b("iPad")}function gvjs_jc(){return gvjs_ic()||gvjs_4b("iPad")||gvjs_4b("iPod")};function gvjs_kc(a){gvjs_kc[" "](a);return a}gvjs_kc[" "]=gvjs_pb;function gvjs_laa(a,b){var c=gvjs_maa;return Object.prototype.hasOwnProperty.call(c,a)?c[a]:c[a]=b(a)};var gvjs_lc=gvjs_4b("Opera"),gvjs_q=gvjs_4b("Trident")||gvjs_4b("MSIE"),gvjs_mc=gvjs_4b(gvjs_ka),gvjs_naa=gvjs_mc||gvjs_q,gvjs_nc=gvjs_4b("Gecko")&&!(gvjs_Tb(gvjs_1b.toLowerCase(),"webkit")&&!gvjs_4b(gvjs_ka))&&!(gvjs_4b("Trident")||gvjs_4b("MSIE"))&&!gvjs_4b(gvjs_ka),gvjs_oc=gvjs_Tb(gvjs_1b.toLowerCase(),"webkit")&&!gvjs_4b(gvjs_ka),gvjs_oaa=gvjs_oc&&gvjs_4b("Mobile"),gvjs_pc=gvjs_4b("Macintosh"),gvjs_qc=gvjs_4b("Windows"),gvjs_rc=gvjs_4b("Linux")||gvjs_4b("CrOS"),gvjs_sc=gvjs_g.navigator||null;
gvjs_sc&&gvjs_Tb(gvjs_sc.appVersion||"","X11");var gvjs_paa=gvjs_4b("Android"),gvjs_qaa=gvjs_ic(),gvjs_raa=gvjs_4b("iPad"),gvjs_saa=gvjs_4b("iPod"),gvjs_taa=gvjs_jc();gvjs_Tb(gvjs_1b.toLowerCase(),"kaios");function gvjs_tc(){var a=gvjs_g.document;return a?a.documentMode:void 0}var gvjs_uc;
a:{var gvjs_vc="",gvjs_wc=function(){var a=gvjs_1b;if(gvjs_nc)return/rv:([^\);]+)(\)|;)/.exec(a);if(gvjs_mc)return/Edge\/([\d\.]+)/.exec(a);if(gvjs_q)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(gvjs_oc)return/WebKit\/(\S+)/.exec(a);if(gvjs_lc)return/(?:Version)[ \/]?(\S+)/.exec(a)}();gvjs_wc&&(gvjs_vc=gvjs_wc?gvjs_wc[1]:"");if(gvjs_q){var gvjs_xc=gvjs_tc();if(null!=gvjs_xc&&gvjs_xc>parseFloat(gvjs_vc)){gvjs_uc=String(gvjs_xc);break a}}gvjs_uc=gvjs_vc}var gvjs_yc=gvjs_uc,gvjs_maa={};
function gvjs_zc(a){return gvjs_laa(a,function(){return 0<=gvjs_Ub(gvjs_yc,a)})}function gvjs_Ac(a){return Number(gvjs_uaa)>=a}var gvjs_Bc;if(gvjs_g.document&&gvjs_q){var gvjs_Cc=gvjs_tc();gvjs_Bc=gvjs_Cc?gvjs_Cc:parseInt(gvjs_yc,10)||void 0}else gvjs_Bc=void 0;var gvjs_uaa=gvjs_Bc;try{(new self.OffscreenCanvas(0,0)).getContext("2d")}catch(a){}var gvjs_vaa=!gvjs_q||gvjs_Ac(9),gvjs_waa=!gvjs_nc&&!gvjs_q||gvjs_q&&gvjs_Ac(9)||gvjs_nc&&gvjs_zc("1.9.1"),gvjs_Dc=gvjs_q&&!gvjs_zc("9"),gvjs_xaa=gvjs_q||gvjs_lc||gvjs_oc;function gvjs_Ec(a,b,c){return Math.min(Math.max(a,b),c)};function gvjs_Fc(a){return a?new gvjs_Gc(gvjs_Hc(a)):gvjs_wb||(gvjs_wb=new gvjs_Gc)}function gvjs_Ic(a,b){gvjs_o(b,function(c,d){c&&typeof c==gvjs_d&&c.Zo&&(c=c.cl());d==gvjs_0a?a.style.cssText=c:d==gvjs_La?a.className=c:"for"==d?a.htmlFor=c:gvjs_Jc.hasOwnProperty(d)?a.setAttribute(gvjs_Jc[d],c):gvjs_Pb(d,"aria-")||gvjs_Pb(d,"data-")?a.setAttribute(d,c):a[d]=c})}
var gvjs_Jc={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",frameborder:"frameBorder",height:gvjs_Ua,maxlength:"maxLength",nonce:"nonce",role:gvjs_Za,rowspan:"rowSpan",type:gvjs_5a,usemap:"useMap",valign:"vAlign",width:gvjs_6a};function gvjs_Kc(a,b,c,d){function e(g){g&&b.appendChild(typeof g===gvjs_e?a.createTextNode(g):g)}for(;d<c.length;d++){var f=c[d];gvjs_rb(f)&&!gvjs_Lc(f)?gvjs_m(gvjs_yaa(f)?gvjs_Eb(f):f,e):e(f)}}
function gvjs_Mc(a,b){b=String(b);"application/xhtml+xml"===a.contentType&&(b=b.toLowerCase());return a.createElement(b)}
function gvjs_Nc(a){if(1!=a.nodeType)return!1;switch(a.tagName){case "APPLET":case "AREA":case "BASE":case "BR":case "COL":case "COMMAND":case "EMBED":case "FRAME":case "HR":case "IMG":case gvjs_oa:case gvjs_na:case "ISINDEX":case "KEYGEN":case "LINK":case "NOFRAMES":case "NOSCRIPT":case "META":case gvjs_wa:case "PARAM":case "SCRIPT":case gvjs_ya:case gvjs_za:case "TRACK":case "WBR":return!1}return!0}function gvjs_Oc(a,b){gvjs_Kc(gvjs_Hc(a),a,arguments,1)}
function gvjs_Pc(a){for(var b;b=a.firstChild;)a.removeChild(b)}function gvjs_Qc(a,b){b.parentNode&&b.parentNode.insertBefore(a,b)}function gvjs_Rc(a,b){b.parentNode&&b.parentNode.insertBefore(a,b.nextSibling)}function gvjs_Sc(a){return a&&a.parentNode?a.parentNode.removeChild(a):null}function gvjs_Tc(a){return gvjs_waa&&void 0!=a.children?a.children:gvjs_zb(a.childNodes,function(b){return 1==b.nodeType})}
function gvjs_Uc(a){return void 0!==a.firstElementChild?a.firstElementChild:gvjs_Vc(a.firstChild,!0)}function gvjs_Wc(a){return void 0!==a.nextElementSibling?a.nextElementSibling:gvjs_Vc(a.nextSibling,!0)}function gvjs_Vc(a,b){for(;a&&1!=a.nodeType;)a=b?a.nextSibling:a.previousSibling;return a}function gvjs_Lc(a){return gvjs_i(a)&&0<a.nodeType}function gvjs_Xc(a){return gvjs_i(a)&&1==a.nodeType}
function gvjs_Yc(a){var b;if(gvjs_xaa&&!(gvjs_q&&gvjs_zc("9")&&!gvjs_zc("10")&&gvjs_g.SVGElement&&a instanceof gvjs_g.SVGElement)&&(b=a.parentElement))return b;b=a.parentNode;return gvjs_Xc(b)?b:null}function gvjs_Zc(a,b){if(!a||!b)return!1;if(a.contains&&1==b.nodeType)return a==b||a.contains(b);if("undefined"!=typeof a.compareDocumentPosition)return a==b||!!(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a}
function gvjs_Hc(a){return 9==a.nodeType?a:a.ownerDocument||a.document}function gvjs__c(a){return a.contentDocument||a.contentWindow.document}function gvjs_0c(a,b){if("textContent"in a)a.textContent=b;else if(3==a.nodeType)a.data=String(b);else if(a.firstChild&&3==a.firstChild.nodeType){for(;a.lastChild!=a.firstChild;)a.removeChild(a.lastChild);a.firstChild.data=String(b)}else gvjs_Pc(a),a.appendChild(gvjs_Hc(a).createTextNode(String(b)))}
var gvjs_zaa={SCRIPT:1,STYLE:1,HEAD:1,IFRAME:1,OBJECT:1},gvjs_1c={IMG:" ",BR:"\n"};function gvjs_2c(a){if(gvjs_Dc&&null!==a&&"innerText"in a)a=a.innerText.replace(/(\r\n|\r|\n)/g,"\n");else{var b=[];gvjs_3c(a,b,!0);a=b.join("")}a=a.replace(/ \xAD /g," ").replace(/\xAD/g,"");a=a.replace(/\u200B/g,"");gvjs_Dc||(a=a.replace(/ +/g," "));" "!=a&&(a=a.replace(/^\s*/,""));return a}
function gvjs_3c(a,b,c){if(!(a.nodeName in gvjs_zaa))if(3==a.nodeType)c?b.push(String(a.nodeValue).replace(/(\r\n|\r|\n)/g,"")):b.push(a.nodeValue);else if(a.nodeName in gvjs_1c)b.push(gvjs_1c[a.nodeName]);else for(a=a.firstChild;a;)gvjs_3c(a,b,c),a=a.nextSibling}function gvjs_yaa(a){if(a&&typeof a.length==gvjs_c){if(gvjs_i(a))return typeof a.item==gvjs_a||typeof a.item==gvjs_e;if(gvjs_j(a))return typeof a.item==gvjs_a}return!1}
function gvjs_4c(a,b,c,d){a&&!c&&(a=a.parentNode);for(c=0;a&&(null==d||c<=d);){if(b(a))return a;a=a.parentNode;c++}return null}function gvjs_Gc(a){this.jd=a||gvjs_g.document||document}gvjs_=gvjs_Gc.prototype;gvjs_.xa=gvjs_Fc;gvjs_.jc=gvjs_f(3);gvjs_.j=gvjs_f(4);gvjs_.getElementsByTagName=function(a,b){return(b||this.jd).getElementsByTagName(String(a))};gvjs_.Fq=gvjs_f(5);gvjs_.nd=gvjs_f(7);gvjs_.LO=gvjs_f(9);gvjs_.Cr=gvjs_Ic;gvjs_.J=gvjs_f(10);
gvjs_.createElement=function(a){return gvjs_Mc(this.jd,a)};gvjs_.createTextNode=function(a){return this.jd.createTextNode(String(a))};gvjs_.zW=gvjs_f(11);gvjs_.To=gvjs_f(12);gvjs_.Dy=gvjs_f(13);gvjs_.appendChild=function(a,b){a.appendChild(b)};gvjs_.append=gvjs_Oc;gvjs_.canHaveChildren=gvjs_Nc;gvjs_.Bc=gvjs_Pc;gvjs_.HZ=gvjs_Qc;gvjs_.Kra=gvjs_Rc;gvjs_.removeNode=gvjs_Sc;gvjs_.Xe=gvjs_Tc;gvjs_.O9=gvjs_Uc;gvjs_.Q9=gvjs_Wc;gvjs_.$o=gvjs_Lc;gvjs_.OZ=gvjs_Xc;gvjs_.GO=gvjs_Yc;gvjs_.contains=gvjs_Zc;
gvjs_.Hoa=gvjs_Hc;gvjs_.P9=gvjs__c;gvjs_.I2=gvjs_0c;gvjs_.Qq=gvjs_f(15);gvjs_.Joa=gvjs_2c;gvjs_.G9=gvjs_4c;var gvjs_5c={aliceblue:"#f0f8ff",antiquewhite:"#faebd7",aqua:"#00ffff",aquamarine:"#7fffd4",azure:"#f0ffff",beige:"#f5f5dc",bisque:"#ffe4c4",black:gvjs_aa,blanchedalmond:"#ffebcd",blue:"#0000ff",blueviolet:"#8a2be2",brown:"#a52a2a",burlywood:"#deb887",cadetblue:"#5f9ea0",chartreuse:"#7fff00",chocolate:"#d2691e",coral:"#ff7f50",cornflowerblue:"#6495ed",cornsilk:"#fff8dc",crimson:"#dc143c",cyan:"#00ffff",darkblue:"#00008b",darkcyan:"#008b8b",darkgoldenrod:"#b8860b",darkgray:"#a9a9a9",darkgreen:"#006400",
darkgrey:"#a9a9a9",darkkhaki:"#bdb76b",darkmagenta:"#8b008b",darkolivegreen:"#556b2f",darkorange:"#ff8c00",darkorchid:"#9932cc",darkred:"#8b0000",darksalmon:"#e9967a",darkseagreen:"#8fbc8f",darkslateblue:"#483d8b",darkslategray:"#2f4f4f",darkslategrey:"#2f4f4f",darkturquoise:"#00ced1",darkviolet:"#9400d3",deeppink:"#ff1493",deepskyblue:"#00bfff",dimgray:"#696969",dimgrey:"#696969",dodgerblue:"#1e90ff",firebrick:"#b22222",floralwhite:"#fffaf0",forestgreen:"#228b22",fuchsia:"#ff00ff",gainsboro:"#dcdcdc",
ghostwhite:"#f8f8ff",gold:"#ffd700",goldenrod:"#daa520",gray:gvjs_ba,green:"#008000",greenyellow:"#adff2f",grey:gvjs_ba,honeydew:"#f0fff0",hotpink:"#ff69b4",indianred:"#cd5c5c",indigo:"#4b0082",ivory:"#fffff0",khaki:"#f0e68c",lavender:"#e6e6fa",lavenderblush:"#fff0f5",lawngreen:"#7cfc00",lemonchiffon:"#fffacd",lightblue:"#add8e6",lightcoral:"#f08080",lightcyan:"#e0ffff",lightgoldenrodyellow:"#fafad2",lightgray:"#d3d3d3",lightgreen:"#90ee90",lightgrey:"#d3d3d3",lightpink:"#ffb6c1",lightsalmon:"#ffa07a",
lightseagreen:"#20b2aa",lightskyblue:"#87cefa",lightslategray:"#778899",lightslategrey:"#778899",lightsteelblue:"#b0c4de",lightyellow:"#ffffe0",lime:"#00ff00",limegreen:"#32cd32",linen:"#faf0e6",magenta:"#ff00ff",maroon:"#800000",mediumaquamarine:"#66cdaa",mediumblue:"#0000cd",mediumorchid:"#ba55d3",mediumpurple:"#9370db",mediumseagreen:"#3cb371",mediumslateblue:"#7b68ee",mediumspringgreen:"#00fa9a",mediumturquoise:"#48d1cc",mediumvioletred:"#c71585",midnightblue:"#191970",mintcream:"#f5fffa",mistyrose:"#ffe4e1",
moccasin:"#ffe4b5",navajowhite:"#ffdead",navy:"#000080",oldlace:"#fdf5e6",olive:"#808000",olivedrab:"#6b8e23",orange:"#ffa500",orangered:"#ff4500",orchid:"#da70d6",palegoldenrod:"#eee8aa",palegreen:"#98fb98",paleturquoise:"#afeeee",palevioletred:"#db7093",papayawhip:"#ffefd5",peachpuff:"#ffdab9",peru:"#cd853f",pink:"#ffc0cb",plum:"#dda0dd",powderblue:"#b0e0e6",purple:"#800080",red:"#ff0000",rosybrown:"#bc8f8f",royalblue:"#4169e1",saddlebrown:"#8b4513",salmon:"#fa8072",sandybrown:"#f4a460",seagreen:"#2e8b57",
seashell:"#fff5ee",sienna:"#a0522d",silver:"#c0c0c0",skyblue:"#87ceeb",slateblue:"#6a5acd",slategray:"#708090",slategrey:"#708090",snow:"#fffafa",springgreen:"#00ff7f",steelblue:"#4682b4",tan:"#d2b48c",teal:"#008080",thistle:"#d8bfd8",tomato:"#ff6347",turquoise:"#40e0d0",violet:"#ee82ee",wheat:"#f5deb3",white:gvjs_ca,whitesmoke:"#f5f5f5",yellow:"#ffff00",yellowgreen:"#9acd32"};function gvjs_6c(a){var b={};a=String(a);var c="#"==a.charAt(0)?a:"#"+a;if(gvjs_7c.test(c))return b.hex=gvjs_8c(c),b.type="hex",b;c=gvjs_9c(a);if(c.length)return b.hex=gvjs_$c(c),b.type="rgb",b;if(gvjs_5c&&(c=gvjs_5c[a.toLowerCase()]))return b.hex=c,b.type="named",b;throw Error(a+" is not a valid color string");}var gvjs_Aaa=/#(.)(.)(.)/;
function gvjs_8c(a){if(!gvjs_7c.test(a))throw Error("'"+a+"' is not a valid hex color");4==a.length&&(a=a.replace(gvjs_Aaa,"#$1$1$2$2$3$3"));return a.toLowerCase()}function gvjs_ad(a){a=gvjs_8c(a);a=parseInt(a.substr(1),16);return[a>>16,a>>8&255,a&255]}function gvjs_bd(a,b,c){a=Number(a);b=Number(b);c=Number(c);if(a!=(a&255)||b!=(b&255)||c!=(c&255))throw Error('"('+a+","+b+","+c+'") is not a valid RGB color');b=a<<16|b<<8|c;return 16>a?"#"+(16777216|b).toString(16).substr(1):"#"+b.toString(16)}
function gvjs_$c(a){return gvjs_bd(a[0],a[1],a[2])}var gvjs_7c=/^#(?:[0-9a-f]{3}){1,2}$/i,gvjs_Baa=/^(?:rgb)?\((0|[1-9]\d{0,2}),\s?(0|[1-9]\d{0,2}),\s?(0|[1-9]\d{0,2})\)$/i;function gvjs_9c(a){var b=a.match(gvjs_Baa);if(b){a=Number(b[1]);var c=Number(b[2]);b=Number(b[3]);if(0<=a&&255>=a&&0<=c&&255>=c&&0<=b&&255>=b)return[a,c,b]}return[]}function gvjs_cd(a,b,c){c=gvjs_Ec(c,0,1);return[Math.round(b[0]+c*(a[0]-b[0])),Math.round(b[1]+c*(a[1]-b[1])),Math.round(b[2]+c*(a[2]-b[2]))]};function gvjs_dd(a,b){if(null==a||""===a||a==gvjs_3a||a==gvjs_b)var c=gvjs_b;else{if(gvjs_i(a))return a.color||"";try{c=gvjs_6c(a).hex}catch(d){if(!b)throw Error("Invalid color: "+a);c=a}}return c};var gvjs_ed="StopIteration"in gvjs_g?gvjs_g.StopIteration:{message:"StopIteration",stack:""};var gvjs_fd={ERAS:["BC","AD"],ERANAMES:["Before Christ","Anno Domini"],NARROWMONTHS:"JFMAMJJASOND".split(""),STANDALONENARROWMONTHS:"JFMAMJJASOND".split(""),MONTHS:[gvjs_qa,gvjs_la,gvjs_sa,gvjs_ga,gvjs_ta,"June","July",gvjs_ha,gvjs_Ba,gvjs_xa,gvjs_va,gvjs_ja],STANDALONEMONTHS:[gvjs_qa,gvjs_la,gvjs_sa,gvjs_ga,gvjs_ta,"June","July",gvjs_ha,gvjs_Ba,gvjs_xa,gvjs_va,gvjs_ja],SHORTMONTHS:["Jan","Feb","Mar","Apr",gvjs_ta,"Jun","Jul","Aug","Sep","Oct","Nov","Dec"],STANDALONESHORTMONTHS:["Jan","Feb","Mar",
"Apr",gvjs_ta,"Jun","Jul","Aug","Sep","Oct","Nov","Dec"],WEEKDAYS:[gvjs_Ca,gvjs_ua,gvjs_Fa,gvjs_Ga,gvjs_Da,gvjs_ma,gvjs_Aa],STANDALONEWEEKDAYS:[gvjs_Ca,gvjs_ua,gvjs_Fa,gvjs_Ga,gvjs_Da,gvjs_ma,gvjs_Aa],SHORTWEEKDAYS:"Sun Mon Tue Wed Thu Fri Sat".split(" "),STANDALONESHORTWEEKDAYS:"Sun Mon Tue Wed Thu Fri Sat".split(" "),NARROWWEEKDAYS:"SMTWTFS".split(""),STANDALONENARROWWEEKDAYS:"SMTWTFS".split(""),SHORTQUARTERS:["Q1","Q2","Q3","Q4"],QUARTERS:["1st quarter","2nd quarter","3rd quarter","4th quarter"],
AMPMS:["AM","PM"],DATEFORMATS:["EEEE, MMMM d, y","MMMM d, y","MMM d, y","M/d/yy"],TIMEFORMATS:["h:mm:ss a zzzz","h:mm:ss a z","h:mm:ss a","h:mm a"],DATETIMEFORMATS:[gvjs_7a,gvjs_7a,gvjs_8a,gvjs_8a],FIRSTDAYOFWEEK:6,WEEKENDRANGE:[5,6],FIRSTWEEKCUTOFFDAY:5},gvjs_gd=gvjs_fd;gvjs_gd=gvjs_fd;function gvjs_hd(a,b){switch(b){case 1:return 0!=a%4||0==a%100&&0!=a%400?28:29;case 5:case 8:case 10:case 3:return 30}return 31}function gvjs_id(a,b,c,d,e){a=new Date(a,b,c);e=e||0;return a.valueOf()+864E5*(((void 0!==d?d:3)-e+7)%7-((a.getDay()+6)%7-e+7)%7)}
function gvjs_jd(a,b,c){typeof a===gvjs_c?(this.date=gvjs_kd(a,b||0,c||1),gvjs_ld(this,c||1)):gvjs_i(a)?(this.date=gvjs_kd(a.getFullYear(),a.getMonth(),a.getDate()),gvjs_ld(this,a.getDate())):(this.date=new Date(gvjs_vb()),a=this.date.getDate(),this.date.setHours(0),this.date.setMinutes(0),this.date.setSeconds(0),this.date.setMilliseconds(0),gvjs_ld(this,a))}function gvjs_kd(a,b,c){b=new Date(a,b,c);0<=a&&100>a&&b.setFullYear(b.getFullYear()-1900);return b}gvjs_=gvjs_jd.prototype;gvjs_.dC=gvjs_gd.FIRSTDAYOFWEEK;
gvjs_.eC=gvjs_gd.FIRSTWEEKCUTOFFDAY;gvjs_.clone=function(){var a=new gvjs_jd(this.date);a.dC=this.dC;a.eC=this.eC;return a};gvjs_.getFullYear=function(){return this.date.getFullYear()};gvjs_.getYear=function(){return this.getFullYear()};gvjs_.getMonth=function(){return this.date.getMonth()};gvjs_.getDate=function(){return this.date.getDate()};gvjs_.getTime=function(){return this.date.getTime()};gvjs_.getDay=function(){return this.date.getDay()};gvjs_.getUTCFullYear=function(){return this.date.getUTCFullYear()};
gvjs_.getUTCMonth=function(){return this.date.getUTCMonth()};gvjs_.getUTCDate=function(){return this.date.getUTCDate()};gvjs_.getUTCDay=function(){return this.date.getDay()};gvjs_.getUTCHours=function(){return this.date.getUTCHours()};gvjs_.getUTCMinutes=function(){return this.date.getUTCMinutes()};gvjs_.getTimezoneOffset=function(){return this.date.getTimezoneOffset()};gvjs_.set=function(a){this.date=new Date(a.getFullYear(),a.getMonth(),a.getDate())};gvjs_.setFullYear=function(a){this.date.setFullYear(a)};
gvjs_.setYear=function(a){this.setFullYear(a)};gvjs_.setMonth=function(a){this.date.setMonth(a)};gvjs_.setDate=function(a){this.date.setDate(a)};gvjs_.setTime=function(a){this.date.setTime(a)};gvjs_.setUTCFullYear=function(a){this.date.setUTCFullYear(a)};gvjs_.setUTCMonth=function(a){this.date.setUTCMonth(a)};gvjs_.setUTCDate=function(a){this.date.setUTCDate(a)};
gvjs_.add=function(a){if(a.Lj||a.months){var b=this.getMonth()+a.months+12*a.Lj,c=this.getYear()+Math.floor(b/12);b%=12;0>b&&(b+=12);var d=Math.min(gvjs_hd(c,b),this.getDate());this.setDate(1);this.setFullYear(c);this.setMonth(b);this.setDate(d)}a.days&&(a=new Date((new Date(this.getYear(),this.getMonth(),this.getDate(),12)).getTime()+864E5*a.days),this.setDate(1),this.setFullYear(a.getFullYear()),this.setMonth(a.getMonth()),this.setDate(a.getDate()),gvjs_ld(this,a.getDate()))};
gvjs_.EA=function(a){return[this.getFullYear(),gvjs_cc(this.getMonth()+1,2),gvjs_cc(this.getDate(),2)].join(a?"-":"")+""};gvjs_.equals=function(a){return!(!a||this.getYear()!=a.getYear()||this.getMonth()!=a.getMonth()||this.getDate()!=a.getDate())};gvjs_.toString=function(){return this.EA()};function gvjs_ld(a,b){a.getDate()!=b&&a.date.setUTCHours(a.date.getUTCHours()+(a.getDate()<b?1:-1))}gvjs_.valueOf=function(){return this.date.valueOf()};function gvjs_md(a,b){a=a.split(".");var c=b||gvjs_g;for(b=0;b<a.length;b++){var d=a[b];if(Array.isArray(c)&&!d.match(/[0-9]+/))a:{c=gvjs_ab(c);for(var e=c.next();!e.done;e=c.next())if(e=e.value,e.name&&e.name===d){c=e;break a}c=null}else if(null!=c[d])c=c[d];else return null}return c}function gvjs_nd(a){return gvjs_qb(a)!=gvjs_d||gvjs_sb(a)?null:a}
function gvjs_od(a,b){a=gvjs_nd(a)||{};if(2==arguments.length){var c=arguments[1];if(!gvjs_nd(c))return a;for(var d in c)if(Array.isArray(c[d]))a[d]=gvjs_Eb(c[d]);else if(gvjs_nd(a[d]))a[d]=gvjs_od(a[d],c[d]);else if(gvjs_nd(c[d]))a[d]=gvjs_od({},c[d]);else if(null==a[d]||null!=c[d])a[d]=c[d]}else if(2<arguments.length)for(c=1,d=arguments.length;c<d;c++)a=gvjs_od(a,arguments[c]);return a};var gvjs_pd;function gvjs_qd(a,b,c,d){this.Je=a||[{}];this.cJ=d||gvjs_Fb(1,this.Je.length);this.xM=b||null;this.PZ=null!=c?c:!1}gvjs_=gvjs_qd.prototype;gvjs_.view=function(a){a=gvjs_rd(this,a);return new gvjs_qd(gvjs_Eb(this.Je),a,this.PZ,gvjs_Eb(this.cJ))};function gvjs_rd(a,b){typeof b===gvjs_e&&(b=[b]);return null!=a.xM?gvjs_sd(a.xM,b):b}
function gvjs_sd(a,b){a=typeof a===gvjs_e?[a]:a;var c=typeof b===gvjs_e?[b]:b;if(0===a.length)return c;if(0===c.length)return a;var d=[];gvjs_m(a,function(e){var f=gvjs_Rb(e);gvjs_m(c,function(g){var h=gvjs_Rb(g);f||h?f?h||d.push(g):d.push(e):d.push(e+"."+g)})});return d}function gvjs_td(a,b,c,d){typeof b===gvjs_e&&(b=[b]);for(var e=0;e<b.length;++e){var f=gvjs_ud(a,b[e],c,d);if(null!=f)return f}return null}function gvjs_ud(a,b,c,d){a=d?a[b]:gvjs_md(b,a);return null!=a&&typeof c===gvjs_a?c(a):a}
gvjs_.Ka=function(a,b){var c=[];null!=b&&c.push(b);a=gvjs_rd(this,a);for(b=this.Je.length-1;0<=b;b--)for(var d=a.length-1;0<=d;d--){var e=gvjs_ud(this.Je[b],a[d],void 0,this.PZ);null!=e&&c.unshift(e)}return c};function gvjs_Caa(a,b,c){var d={};a=a.Ka(b,c);gvjs_yb(a,function(e){typeof e===gvjs_d&&gvjs_od(d,e)});return d}gvjs_.ea=function(a,b,c){a=gvjs_rd(this,a);for(var d=0;d<this.Je.length;d++){var e=gvjs_td(this.Je[d],a,c,this.PZ);if(null!=e)return e}e=null!=b&&c?c(b):b;return null!=e?e:null};
gvjs_.nb=function(a,b,c){a=gvjs_Caa(this,a,b);c&&(a=c(a));return a||{}};function gvjs_vd(a,b,c,d,e,f){function g(h){return b(h,f)}a=a.ea(d,e,g);null==a&&(a=g(c),null==a&&(a=c));if(null==a)throw Error("Unexpected null value for "+d);return a}function gvjs_wd(a,b,c,d){a=a.ea(c,null,function(e){return b(e,d)});return null==a?null:a}function gvjs_xd(a,b){a=null!=a&&typeof a!==gvjs_d?String(a):null;return b?Array.isArray(b)?gvjs_Db(b,a)?a:null:gvjs_Mb(b,a)?a:null:a}
function gvjs_r(a,b,c,d){return gvjs_vd(a,gvjs_xd,"",b,c,d)}gvjs_.ob=function(a,b){return gvjs_wd(this,gvjs_xd,a,b)};function gvjs_yd(a,b){if(null==a)return null;typeof a===gvjs_e&&(a=[a]);return Array.isArray(a)?gvjs_zb(gvjs_n(a,function(c){return gvjs_xd(c,b)}),function(c){return null!=c}):null}gvjs_.MC=function(a,b){return gvjs_wd(this,gvjs_yd,a,b)};
function gvjs_zd(a){if(null==a)return null;if(typeof a===gvjs_Ka)return a;a=String(a);return"1"===a||a.toLowerCase()===gvjs_4a?!0:"0"===a||a.toLowerCase()===gvjs_Ra?!1:null}function gvjs_s(a,b,c){return gvjs_vd(a,gvjs_zd,!1,b,c)}gvjs_.Nq=function(a){return gvjs_wd(this,gvjs_zd,a)};function gvjs_Ad(a){if(null==a)return null;if(typeof a===gvjs_c)return a;a=gvjs_fc(String(a));return isNaN(a)?null:a}function gvjs_t(a,b,c){return gvjs_vd(a,gvjs_Ad,0,b,c)}
gvjs_.Da=function(a){return gvjs_wd(this,gvjs_Ad,a)};function gvjs_Bd(a){return null==a?null:typeof a===gvjs_c||typeof a===gvjs_e||typeof a===gvjs_Ka?a:null}gvjs_.qt=function(a){return gvjs_wd(this,gvjs_Bd,a)};function gvjs_Cd(a){return null==a?null:Array.isArray(a)?gvjs_zb(gvjs_n(a,gvjs_Ad),function(b){return null!=b}):null}gvjs_.xI=function(a){return gvjs_wd(this,gvjs_Cd,a)};function gvjs_Dd(a){a=gvjs_Ad(a);return null!=a&&0<=a?a:null}function gvjs_Ed(a,b,c){return gvjs_vd(a,gvjs_Dd,0,b,c)}
gvjs_.LC=function(a){return gvjs_wd(this,gvjs_Dd,a)};function gvjs_Fd(a){a=gvjs_Ad(a);return null!=a?gvjs_Ec(a,0,1):null}gvjs_.yra=function(a){return gvjs_wd(this,gvjs_Fd,a)};function gvjs_Gd(a,b){if(null==a)return null;if(""===a)return gvjs_b;if(typeof a===gvjs_d)return a.color||a.lighter||a.darker?a:null;a=gvjs_xd(a);if(Array.isArray(b)&&gvjs_Db(b,a))return a;try{return gvjs_dd(a)}catch(c){return null}}gvjs_.cz=function(a,b){return gvjs_wd(this,gvjs_Gd,a,b)};
function gvjs_Hd(a,b){b=null!=b?b:1;var c=gvjs_Ad(a);null==c&&(a=gvjs_xd(a),null!=a&&gvjs_Qb(a)&&(c=a.slice(0,-1),c=b*Number(c)/100));null!=c&&(c=0===b?0:b*gvjs_Ec(c/b,0,1));return c}gvjs_.el=function(a,b){return gvjs_wd(this,gvjs_Hd,a,b)};
gvjs_pd={string:gvjs_qd.prototype.ob,number:gvjs_qd.prototype.Da,"boolean":gvjs_qd.prototype.Nq,numberOrString:[gvjs_c,gvjs_e],primitive:gvjs_qd.prototype.qt,ratio:gvjs_qd.prototype.yra,nonNegative:gvjs_qd.prototype.LC,absOrPercentage:gvjs_qd.prototype.el,arrayOfNumber:gvjs_qd.prototype.xI,arrayOfString:gvjs_qd.prototype.MC,color:gvjs_qd.prototype.cz,object:gvjs_qd.prototype.nb};function gvjs_Id(){}
function gvjs_Jd(a){if(typeof a==gvjs_c){var b=new gvjs_Id;b.r3=a;var c=a;if(0==c)c="Etc/GMT";else{var d=["Etc/GMT",0>c?"-":"+"];c=Math.abs(c);d.push(Math.floor(c/60)%100);c%=60;0!=c&&d.push(":",gvjs_cc(c,2));c=d.join("")}b.X3=c;c=a;0==c?c="UTC":(d=["UTC",0>c?"+":"-"],c=Math.abs(c),d.push(Math.floor(c/60)%100),c%=60,0!=c&&d.push(":",c),c=d.join(""));a=gvjs_Kd(a);b.OT=[c,c];b.Zw={wBa:a,u5:a};b.KA=[];return b}b=new gvjs_Id;b.X3=a.id;b.r3=-a.std_offset;b.OT=a.names;b.Zw=a.names_ext;b.KA=a.transitions;
return b}function gvjs_Kd(a){var b=["GMT"];b.push(0>=a?"+":"-");a=Math.abs(a);b.push(gvjs_cc(Math.floor(a/60)%100,2),":",gvjs_cc(a%60,2));return b.join("")}gvjs_=gvjs_Id.prototype;gvjs_.getTimeZoneData=function(){return{id:this.X3,std_offset:-this.r3,names:gvjs_Eb(this.OT),names_ext:gvjs_p(this.Zw),transitions:gvjs_Eb(this.KA)}};
gvjs_.getDaylightAdjustment=function(a){a=Date.UTC(a.getUTCFullYear(),a.getUTCMonth(),a.getUTCDate(),a.getUTCHours(),a.getUTCMinutes())/36E5;for(var b=0;b<this.KA.length&&a>=this.KA[b];)b+=2;return 0==b?0:this.KA[b-1]};gvjs_.getGMTString=function(a){return gvjs_Kd(this.getOffset(a))};gvjs_.getLongName=function(a){return this.OT[this.isDaylightTime(a)?3:1]};gvjs_.getOffset=function(a){return this.r3-this.getDaylightAdjustment(a)};
gvjs_.getRFCTimeZoneString=function(a){a=-this.getOffset(a);var b=[0>a?"-":"+"];a=Math.abs(a);b.push(gvjs_cc(Math.floor(a/60)%100,2),gvjs_cc(a%60,2));return b.join("")};gvjs_.getShortName=function(a){return this.OT[this.isDaylightTime(a)?2:0]};gvjs_.getTimeZoneId=function(){return this.X3};gvjs_.isDaylightTime=function(a){return 0<this.getDaylightAdjustment(a)};function gvjs_Ld(a){this.qR=[];this.Qe=gvjs_gd;typeof a==gvjs_c?this.lM(a):this.gs(a)}var gvjs_Md=[/^'(?:[^']|'')*('|$)/,/^(?:G+|y+|Y+|M+|k+|S+|E+|a+|h+|K+|H+|c+|L+|Q+|d+|m+|s+|v+|V+|w+|z+|Z+)/,/^[^'GyYMkSEahKHcLQdmsvVwzZ]+/];function gvjs_Nd(a){return a.getHours?a.getHours():0}
gvjs_Ld.prototype.gs=function(a){for(gvjs_Daa&&(a=a.replace(/\u200f/g,""));a;){for(var b=a,c=0;c<gvjs_Md.length;++c){var d=a.match(gvjs_Md[c]);if(d){var e=d[0];a=a.substring(e.length);0==c&&("''"==e?e="'":(e=e.substring(1,"'"==d[1]?e.length-1:e.length),e=e.replace(/''/g,"'")));this.qR.push({text:e,type:c});break}}if(b===a)throw Error("Malformed pattern part: "+a);}};
gvjs_Ld.prototype.format=function(a,b){if(!a)throw Error("The date to format must be non-null.");var c=b?6E4*(a.getTimezoneOffset()-b.getOffset(a)):0,d=c?new Date(a.getTime()+c):a,e=d;b&&d.getTimezoneOffset()!=a.getTimezoneOffset()&&(e=6E4*(d.getTimezoneOffset()-a.getTimezoneOffset()),d=new Date(d.getTime()+e),c+=0<c?-864E5:864E5,e=new Date(a.getTime()+c));c=[];for(var f=0;f<this.qR.length;++f){var g=this.qR[f].text;1==this.qR[f].type?c.push(gvjs_Eaa(this,g,a,d,e,b)):c.push(g)}return c.join("")};
gvjs_Ld.prototype.lM=function(a){if(4>a)var b=this.Qe.DATEFORMATS[a];else if(8>a)b=this.Qe.TIMEFORMATS[a-4];else if(12>a)b=this.Qe.DATETIMEFORMATS[a-8],b=b.replace("{1}",this.Qe.DATEFORMATS[a-8]),b=b.replace("{0}",this.Qe.TIMEFORMATS[a-8]);else{this.lM(10);return}this.gs(b)};function gvjs_Od(a,b){b=String(b);a=a.Qe||gvjs_gd;if(void 0!==a.Dja){for(var c=[],d=0;d<b.length;d++){var e=b.charCodeAt(d);c.push(48<=e&&57>=e?String.fromCharCode(a.Dja+e-48):b.charAt(d))}b=c.join("")}return b}var gvjs_Daa=!1;
function gvjs_Pd(a){if(!(a.getHours&&a.getSeconds&&a.getMinutes))throw Error("The date to format has no time (probably a goog.date.Date). Use Date or goog.date.DateTime, or use a pattern without time fields.");}
function gvjs_Eaa(a,b,c,d,e,f){var g=b.length;switch(b.charAt(0)){case "G":return c=0<d.getFullYear()?1:0,4<=g?a.Qe.ERANAMES[c]:a.Qe.ERAS[c];case "y":return c=d.getFullYear(),0>c&&(c=-c),2==g&&(c%=100),gvjs_Od(a,gvjs_cc(c,g));case "Y":return c=(new Date(gvjs_id(d.getFullYear(),d.getMonth(),d.getDate(),a.Qe.FIRSTWEEKCUTOFFDAY,a.Qe.FIRSTDAYOFWEEK))).getFullYear(),0>c&&(c=-c),2==g&&(c%=100),gvjs_Od(a,gvjs_cc(c,g));case "M":a:switch(c=d.getMonth(),g){case 5:g=a.Qe.NARROWMONTHS[c];break a;case 4:g=a.Qe.MONTHS[c];
break a;case 3:g=a.Qe.SHORTMONTHS[c];break a;default:g=gvjs_Od(a,gvjs_cc(c+1,g))}return g;case "k":return gvjs_Pd(e),gvjs_Od(a,gvjs_cc(gvjs_Nd(e)||24,g));case "S":return gvjs_Od(a,(e.getMilliseconds()/1E3).toFixed(Math.min(3,g)).substr(2)+(3<g?gvjs_cc(0,g-3):""));case "E":return c=d.getDay(),4<=g?a.Qe.WEEKDAYS[c]:a.Qe.SHORTWEEKDAYS[c];case "a":return gvjs_Pd(e),g=gvjs_Nd(e),a.Qe.AMPMS[12<=g&&24>g?1:0];case "h":return gvjs_Pd(e),gvjs_Od(a,gvjs_cc(gvjs_Nd(e)%12||12,g));case "K":return gvjs_Pd(e),gvjs_Od(a,
gvjs_cc(gvjs_Nd(e)%12,g));case "H":return gvjs_Pd(e),gvjs_Od(a,gvjs_cc(gvjs_Nd(e),g));case "c":a:switch(c=d.getDay(),g){case 5:g=a.Qe.STANDALONENARROWWEEKDAYS[c];break a;case 4:g=a.Qe.STANDALONEWEEKDAYS[c];break a;case 3:g=a.Qe.STANDALONESHORTWEEKDAYS[c];break a;default:g=gvjs_Od(a,gvjs_cc(c,1))}return g;case "L":a:switch(c=d.getMonth(),g){case 5:g=a.Qe.STANDALONENARROWMONTHS[c];break a;case 4:g=a.Qe.STANDALONEMONTHS[c];break a;case 3:g=a.Qe.STANDALONESHORTMONTHS[c];break a;default:g=gvjs_Od(a,gvjs_cc(c+
1,g))}return g;case "Q":return c=Math.floor(d.getMonth()/3),4>g?a.Qe.SHORTQUARTERS[c]:a.Qe.QUARTERS[c];case "d":return gvjs_Od(a,gvjs_cc(d.getDate(),g));case "m":return gvjs_Pd(e),gvjs_Od(a,gvjs_cc(e.getMinutes(),g));case "s":return gvjs_Pd(e),gvjs_Od(a,gvjs_cc(e.getSeconds(),g));case "v":return g=f||gvjs_Jd(c.getTimezoneOffset()),g.getTimeZoneId();case "V":return a=f||gvjs_Jd(c.getTimezoneOffset()),2>=g?g=a.getTimeZoneId():(g=a,g=g.isDaylightTime(c)?void 0!==g.Zw.Wha?g.Zw.Wha:g.Zw.DST_GENERIC_LOCATION:
void 0!==g.Zw.u5?g.Zw.u5:g.Zw.STD_GENERIC_LOCATION),g;case "w":return c=gvjs_id(e.getFullYear(),e.getMonth(),e.getDate(),a.Qe.FIRSTWEEKCUTOFFDAY,a.Qe.FIRSTDAYOFWEEK),gvjs_Od(a,gvjs_cc(Math.floor(Math.round((c-(new Date((new Date(c)).getFullYear(),0,1)).valueOf())/864E5)/7)+1,g));case "z":return a=f||gvjs_Jd(c.getTimezoneOffset()),4>g?a.getShortName(c):a.getLongName(c);case "Z":return b=f||gvjs_Jd(c.getTimezoneOffset()),4>g?b.getRFCTimeZoneString(c):gvjs_Od(a,b.getGMTString(c));default:return""}};var gvjs_Qd={YEAR_FULL:"y",YEAR_FULL_WITH_ERA:"y G",YEAR_MONTH_ABBR:"MMM y",YEAR_MONTH_FULL:"MMMM y",YBa:"MM/y",MONTH_DAY_ABBR:"MMM d",MONTH_DAY_FULL:"MMMM dd",MONTH_DAY_SHORT:"M/d",MONTH_DAY_MEDIUM:"MMMM d",MONTH_DAY_YEAR_MEDIUM:"MMM d, y",WEEKDAY_MONTH_DAY_MEDIUM:"EEE, MMM d",WEEKDAY_MONTH_DAY_YEAR_MEDIUM:"EEE, MMM d, y",DAY_ABBR:"d",LAa:"MMM d, h:mm a zzzz"},gvjs_Rd=gvjs_Qd;gvjs_Rd=gvjs_Qd;var gvjs_Sd={h5:{1E3:{other:"0K"},1E4:{other:"00K"},1E5:{other:"000K"},1E6:{other:"0M"},1E7:{other:"00M"},1E8:{other:"000M"},1E9:{other:"0B"},1E10:{other:"00B"},1E11:{other:"000B"},1E12:{other:"0T"},1E13:{other:"00T"},1E14:{other:"000T"}},Nha:{1E3:{other:"0 thousand"},1E4:{other:"00 thousand"},1E5:{other:"000 thousand"},1E6:{other:"0 million"},1E7:{other:"00 million"},1E8:{other:"000 million"},1E9:{other:"0 billion"},1E10:{other:"00 billion"},1E11:{other:"000 billion"},1E12:{other:"0 trillion"},1E13:{other:"00 trillion"},
1E14:{other:"000 trillion"}}},gvjs_Td=gvjs_Sd;gvjs_Td=gvjs_Sd;function gvjs_Faa(a,b){var c=["0"];b=gvjs_Ud[b];if(!b)return a;b=b[0]&7;if(0<b){c.push(".");for(var d=0;d<b;d++)c.push("0")}return a.replace(/0.00/g,c.join(""))}
var gvjs_Ud={AED:[2,"dh","\u062f.\u0625."],ALL:[0,"Lek","Lek"],AUD:[2,"$","AU$"],BDT:[2,"\u09f3","Tk"],BGN:[2,"lev","lev"],BRL:[2,"R$","R$"],CAD:[2,"$","C$"],CDF:[2,"FrCD","CDF"],CHF:[2,"CHF","CHF"],CLP:[0,"$","CL$"],CNY:[2,"\u00a5","RMB\u00a5"],COP:[32,"$","COL$"],CRC:[0,"\u20a1","CR\u20a1"],CZK:[50,"K\u010d","K\u010d"],DKK:[50,"kr.","kr."],DOP:[2,"RD$","RD$"],EGP:[2,"\u00a3","LE"],ETB:[2,"Birr","Birr"],EUR:[2,"\u20ac","\u20ac"],GBP:[2,"\u00a3","GB\u00a3"],HKD:[2,"$","HK$"],HRK:[2,"kn","kn"],HUF:[34,
"Ft","Ft"],IDR:[0,"Rp","Rp"],ILS:[34,"\u20aa","IL\u20aa"],INR:[2,"\u20b9","Rs"],IRR:[0,"Rial","IRR"],ISK:[0,"kr","kr"],JMD:[2,"$","JA$"],JPY:[0,"\u00a5","JP\u00a5"],KRW:[0,"\u20a9","KR\u20a9"],LKR:[2,"Rs","SLRs"],LTL:[2,"Lt","Lt"],MNT:[0,"\u20ae","MN\u20ae"],MVR:[2,"Rf","MVR"],MXN:[2,"$","Mex$"],MYR:[2,"RM","RM"],NOK:[50,"kr","NOkr"],PAB:[2,"B/.","B/."],PEN:[2,"S/.","S/."],PHP:[2,"\u20b1","PHP"],PKR:[0,"Rs","PKRs."],PLN:[50,"z\u0142","z\u0142"],RON:[2,"RON","RON"],RSD:[0,"din","RSD"],RUB:[50,"\u20bd",
"RUB"],SAR:[2,"Rial","Rial"],SEK:[50,"kr","kr"],SGD:[2,"$","S$"],THB:[2,"\u0e3f","THB"],TRY:[2,"\u20ba","TRY"],TWD:[2,"NT$","NT$"],TZS:[0,"TSh","TSh"],UAH:[2,"\u0433\u0440\u043d.","UAH"],USD:[2,"$","US$"],UYU:[2,"$","$U"],VND:[48,"\u20ab","VN\u20ab"],YER:[0,"Rial","Rial"],ZAR:[2,"R","ZAR"]};var gvjs_Vd={DECIMAL_SEP:".",GROUP_SEP:",",PERCENT:"%",FU:"0",Sia:"+",n5:"-",j5:"E",p5:"\u2030",xU:"\u221e",Hia:"NaN",DECIMAL_PATTERN:"#,##0.###",dja:"#E0",AU:"#,##0%",Oha:"\u00a4#,##0.00",Sha:"USD"},gvjs_Wd=gvjs_Vd,gvjs_Xd=gvjs_Vd;gvjs_Xd=gvjs_Wd=gvjs_Vd;function gvjs_Yd(a,b,c,d){var e;if(e=b){a:if(b&&3===b.length){for(e=0;3>e;e++){var f=b[e];if("A">f||"Z"<f&&"a">f||"z"<f){e=!1;break a}}e=!0}else e=!1;e=!e}if(e)throw new TypeError("Currency must be valid ISO code");this.Ora=b?b.toUpperCase():null;this.Zla=c||0;this.Hua=d||null;this.mJ=40;this.jp=1;this.Cm=0;this.$q=3;this.FQ=this.Nt=0;this.V2=this.Kga=!1;this.VJ=this.Rz="";this.ow=gvjs_Zd(this).n5;this.ED="";this.Yf=1;this.Bz=!1;this.Py=[];this.VT=this.e8=!1;this.HG=0;this.wM=null;typeof a==gvjs_c?
this.lM(a):this.gs(a)}var gvjs__d=!1;function gvjs_Zd(a){return a.Hua||(gvjs__d?gvjs_Xd:gvjs_Wd)}function gvjs_0d(a){return a.Ora||gvjs_Zd(a).Sha}gvjs_=gvjs_Yd.prototype;gvjs_.setMinimumFractionDigits=function(a){if(0<this.Cm&&0<a)throw Error(gvjs_ia);this.Nt=a;return this};gvjs_.setMaximumFractionDigits=function(a){if(308<a)throw Error("Unsupported maximum fraction digits: "+a);this.$q=a;return this};gvjs_.setSignificantDigits=function(a){if(0<this.Nt&&0<=a)throw Error(gvjs_ia);this.Cm=a;return this};
gvjs_.getSignificantDigits=function(){return this.Cm};gvjs_.setShowTrailingZeros=function(a){this.V2=a;return this};gvjs_.setBaseFormatting=function(a){this.wM=a;return this};gvjs_.getBaseFormatting=function(){return this.wM};
gvjs_.gs=function(a){this.gd=a.replace(/ /g,"\u00a0");var b=[0];this.Rz=gvjs_1d(this,a,b);for(var c=b[0],d=-1,e=0,f=0,g=0,h=-1,k=a.length,l=!0;b[0]<k&&l;b[0]++)switch(a.charAt(b[0])){case "#":0<f?g++:e++;0<=h&&0>d&&h++;break;case "0":if(0<g)throw Error('Unexpected "0" in pattern "'+a+'"');f++;0<=h&&0>d&&h++;break;case ",":0<h&&this.Py.push(h);h=0;break;case ".":if(0<=d)throw Error('Multiple decimal separators in pattern "'+a+'"');d=e+f+g;break;case "E":if(this.VT)throw Error('Multiple exponential symbols in pattern "'+
a+'"');this.VT=!0;this.FQ=0;b[0]+1<k&&"+"==a.charAt(b[0]+1)&&(b[0]++,this.Kga=!0);for(;b[0]+1<k&&"0"==a.charAt(b[0]+1);)b[0]++,this.FQ++;if(1>e+f||1>this.FQ)throw Error('Malformed exponential pattern "'+a+'"');l=!1;break;default:b[0]--,l=!1}0==f&&0<e&&0<=d&&(f=d,0==f&&f++,g=e-f,e=f-1,f=1);if(0>d&&0<g||0<=d&&(d<e||d>e+f)||0==h)throw Error('Malformed pattern "'+a+'"');g=e+f+g;this.$q=0<=d?g-d:0;0<=d&&(this.Nt=e+f-d,0>this.Nt&&(this.Nt=0));this.jp=(0<=d?d:g)-e;this.VT&&(this.mJ=e+this.jp,0==this.$q&&
0==this.jp&&(this.jp=1));this.Py.push(Math.max(0,h));this.e8=0==d||d==g;c=b[0]-c;this.VJ=gvjs_1d(this,a,b);b[0]<a.length&&";"==a.charAt(b[0])?(b[0]++,1!=this.Yf&&(this.Bz=!0),this.ow=gvjs_1d(this,a,b),b[0]+=c,this.ED=gvjs_1d(this,a,b)):(this.ow+=this.Rz,this.ED+=this.VJ)};
gvjs_.lM=function(a){switch(a){case 1:this.gs(gvjs_Zd(this).DECIMAL_PATTERN);break;case 2:this.gs(gvjs_Zd(this).dja);break;case 3:this.gs(gvjs_Zd(this).AU);break;case 4:this.gs(gvjs_Faa(gvjs_Zd(this).Oha,gvjs_0d(this)));break;case 5:gvjs_2d(this,1);break;case 6:gvjs_2d(this,2);break;default:throw Error("Unsupported pattern type.");}};function gvjs_2d(a,b){a.HG=b;a.gs(gvjs_Zd(a).DECIMAL_PATTERN);a.setMinimumFractionDigits(0);a.setMaximumFractionDigits(2);a.setSignificantDigits(2)}
gvjs_.parse=function(a,b){b=b||[0];if(0!=this.HG)throw Error("Parsing of compact numbers is unimplemented");a=a.replace(/ |\u202f/g,"\u00a0");var c=a.indexOf(this.Rz,b[0])==b[0],d=a.indexOf(this.ow,b[0])==b[0];c&&d&&(this.Rz.length>this.ow.length?d=!1:this.Rz.length<this.ow.length&&(c=!1));c?b[0]+=this.Rz.length:d&&(b[0]+=this.ow.length);if(a.indexOf(gvjs_Zd(this).xU,b[0])==b[0]){b[0]+=gvjs_Zd(this).xU.length;var e=Infinity}else{e=a;var f=!1,g=!1,h=!1,k=-1,l=1,m=gvjs_Zd(this).DECIMAL_SEP,n=gvjs_Zd(this).GROUP_SEP,
p=gvjs_Zd(this).j5;if(0!=this.HG)throw Error("Parsing of compact style numbers is not implemented");n=n.replace(/\u202f/g,"\u00a0");for(var q="";b[0]<e.length;b[0]++){var r=e.charAt(b[0]),t=gvjs_3d(this,r);if(0<=t&&9>=t)q+=t,h=!0;else if(r==m.charAt(0)){if(f||g)break;q+=".";f=!0}else if(r==n.charAt(0)&&("\u00a0"!=n.charAt(0)||b[0]+1<e.length&&0<=gvjs_3d(this,e.charAt(b[0]+1)))){if(f||g)break}else if(r==p.charAt(0)){if(g)break;q+="E";g=!0;k=b[0]}else if("+"==r||"-"==r){if(h&&k!=b[0]-1)break;q+=r}else if(1==
this.Yf&&r==gvjs_Zd(this).PERCENT.charAt(0)){if(1!=l)break;l=100;if(h){b[0]++;break}}else if(1==this.Yf&&r==gvjs_Zd(this).p5.charAt(0)){if(1!=l)break;l=1E3;if(h){b[0]++;break}}else break}1!=this.Yf&&(l=this.Yf);e=parseFloat(q)/l}if(c){if(a.indexOf(this.VJ,b[0])!=b[0])return NaN;b[0]+=this.VJ.length}else if(d){if(a.indexOf(this.ED,b[0])!=b[0])return NaN;b[0]+=this.ED.length}return d?-e:e};
gvjs_.format=function(a){if(isNaN(a))return gvjs_Zd(this).Hia;var b=[];var c=null===this.wM?a:this.wM;if(0==this.HG)c=gvjs_4d;else{c=Math.abs(c);var d=gvjs_5d(this,1>=c?0:gvjs_6d(c)).divisorBase;c=gvjs_5d(this,d+gvjs_6d(gvjs_7d(this,gvjs_8d(c,-d)).zaa))}a=gvjs_8d(a,-c.divisorBase);(d=0>a||0==a&&0>1/a)?c.k0?b.push(c.k0):(b.push(c.prefix),b.push(this.ow)):(b.push(c.prefix),b.push(this.Rz));if(isFinite(a))if(a=a*(d?-1:1)*this.Yf,this.VT)if(0==a)gvjs_9d(this,a,this.jp,b),gvjs_$d(this,0,b);else{var e=
Math.floor(Math.log(a)/Math.log(10)+2E-15);a=gvjs_8d(a,-e);var f=this.jp;1<this.mJ&&this.mJ>this.jp?(f=e%this.mJ,0>f&&(f=this.mJ+f),a=gvjs_8d(a,f),e-=f,f=1):1>this.jp?(e++,a=gvjs_8d(a,-1)):(e-=this.jp-1,a=gvjs_8d(a,this.jp-1));gvjs_9d(this,a,f,b);gvjs_$d(this,e,b)}else gvjs_9d(this,a,this.jp,b);else b.push(gvjs_Zd(this).xU);d?c.l0?b.push(c.l0):(b.push(c.suffix),b.push(this.ED)):(b.push(c.suffix),b.push(this.VJ));return b.join("")};
function gvjs_7d(a,b){var c=gvjs_8d(b,a.$q);0<a.Cm&&(c=gvjs_ae(c,a.Cm,a.$q));c=Math.round(c);isFinite(c)?(b=Math.floor(gvjs_8d(c,-a.$q)),a=Math.floor(c-gvjs_8d(b,a.$q))):a=0;return{zaa:b,eoa:a}}
function gvjs_9d(a,b,c,d){if(a.Nt>a.$q)throw Error("Min value must be less than max value");d||(d=[]);b=gvjs_7d(a,b);var e=b.zaa,f=b.eoa,g=0==e?0:gvjs_6d(e)+1,h=0<a.Nt||0<f||a.V2&&g<a.Cm;b=a.Nt;h&&(b=a.V2&&0<a.Cm?a.Cm-g:a.Nt);var k="";for(g=e;1E20<g;)k="0"+k,g=Math.round(gvjs_8d(g,-1));k=g+k;var l=gvjs_Zd(a).DECIMAL_SEP;g=gvjs_Zd(a).FU.charCodeAt(0);var m=k.length,n=0;if(0<e||0<c){for(e=m;e<c;e++)d.push(String.fromCharCode(g));if(2<=a.Py.length)for(c=1;c<a.Py.length;c++)n+=a.Py[c];c=m-n;if(0<c){e=
a.Py;n=m=0;for(var p,q=gvjs_Zd(a).GROUP_SEP,r=k.length,t=0;t<r;t++)if(d.push(String.fromCharCode(g+1*Number(k.charAt(t)))),1<r-t)if(p=e[n],t<c){var u=c-t;(1===p||0<p&&1===u%p)&&d.push(q)}else n<e.length&&(t===c?n+=1:p===t-c-m+1&&(d.push(q),m+=p,n+=1))}else{c=k;k=a.Py;e=gvjs_Zd(a).GROUP_SEP;p=c.length;q=[];for(m=k.length-1;0<=m&&0<p;m--){n=k[m];for(r=0;r<n&&0<=p-r-1;r++)q.push(String.fromCharCode(g+1*Number(c.charAt(p-r-1))));p-=n;0<p&&q.push(e)}d.push.apply(d,q.reverse())}}else h||d.push(String.fromCharCode(g));
(a.e8||h)&&d.push(l);f=String(f);h=f.split("e+");2==h.length&&(f=String(gvjs_ae(parseFloat(h[0]),a.Cm,1)),f=f.replace(".",""),f+=gvjs_bc("0",parseInt(h[1],10)-f.length+1));a.$q+1>f.length&&(f="1"+gvjs_bc("0",a.$q-f.length)+f);for(a=f.length;"0"==f.charAt(a-1)&&a>b+1;)a--;for(e=1;e<a;e++)d.push(String.fromCharCode(g+1*Number(f.charAt(e))))}
function gvjs_$d(a,b,c){c.push(gvjs_Zd(a).j5);0>b?(b=-b,c.push(gvjs_Zd(a).n5)):a.Kga&&c.push(gvjs_Zd(a).Sia);b=""+b;for(var d=gvjs_Zd(a).FU,e=b.length;e<a.FQ;e++)c.push(d);c.push(b)}function gvjs_3d(a,b){b=b.charCodeAt(0);if(48<=b&&58>b)return b-48;a=gvjs_Zd(a).FU.charCodeAt(0);return a<=b&&b<a+10?b-a:-1}
function gvjs_1d(a,b,c){for(var d="",e=!1,f=b.length;c[0]<f;c[0]++){var g=b.charAt(c[0]);if("'"==g)c[0]+1<f&&"'"==b.charAt(c[0]+1)?(c[0]++,d+="'"):e=!e;else if(e)d+=g;else switch(g){case "#":case "0":case ",":case ".":case ";":return d;case "\u00a4":if(c[0]+1<f&&"\u00a4"==b.charAt(c[0]+1))c[0]++,d+=gvjs_0d(a);else switch(a.Zla){case 0:g=gvjs_0d(a);d+=g in gvjs_Ud?gvjs_Ud[g][1]:g;break;case 2:g=gvjs_0d(a);var h=gvjs_Ud[g];d+=h?g==h[1]?g:g+" "+h[1]:g;break;case 1:g=gvjs_0d(a),d+=g in gvjs_Ud?gvjs_Ud[g][2]:
g}break;case "%":if(!a.Bz&&1!=a.Yf)throw Error(gvjs_Ea);if(a.Bz&&100!=a.Yf)throw Error(gvjs_pa);a.Yf=100;a.Bz=!1;d+=gvjs_Zd(a).PERCENT;break;case "\u2030":if(!a.Bz&&1!=a.Yf)throw Error(gvjs_Ea);if(a.Bz&&1E3!=a.Yf)throw Error(gvjs_pa);a.Yf=1E3;a.Bz=!1;d+=gvjs_Zd(a).p5;break;default:d+=g}}return d}var gvjs_4d={divisorBase:0,k0:"",l0:"",prefix:"",suffix:""};
function gvjs_5d(a,b){a=1==a.HG?gvjs_Td.h5:gvjs_Td.Nha;null==a&&(a=gvjs_Td.h5);if(3>b)return gvjs_4d;b=Math.min(14,b);var c=a[gvjs_8d(1,b)];for(--b;!c&&3<=b;)c=a[gvjs_8d(1,b)],b--;if(!c)return gvjs_4d;c=c.other;var d=a="",e=c.indexOf(";");0<=e&&(c=c.substring(0,e),e=c.substring(e+1))&&(d=/([^0]*)(0+)(.*)/.exec(e),a=d[1],d=d[3]);return c&&"0"!=c?(c=/([^0]*)(0+)(.*)/.exec(c))?{divisorBase:b+1-(c[2].length-1),k0:a,l0:d,prefix:c[1],suffix:c[3]}:gvjs_4d:gvjs_4d}
function gvjs_6d(a){if(!isFinite(a))return 0<a?a:0;for(var b=0;1<=(a/=10);)b++;return b}function gvjs_8d(a,b){if(!a||!isFinite(a)||0==b)return a;a=String(a).split("e");return parseFloat(a[0]+"e"+(parseInt(a[1]||0,10)+b))}function gvjs_be(a,b){return a&&isFinite(a)?gvjs_8d(Math.round(gvjs_8d(a,b)),-b):a}function gvjs_ae(a,b,c){if(!a)return a;b=b-gvjs_6d(a)-1;return b<-c?gvjs_be(a,-c):gvjs_be(a,b)}
gvjs_Yd.prototype.isCurrencyCodeBeforeValue=function(){var a=this.gd.indexOf("\u00a4"),b=this.gd.indexOf("#"),c=this.gd.indexOf("0"),d=Number.MAX_VALUE;0<=b&&b<d&&(d=b);0<=c&&c<d&&(d=c);return a<d};gvjs_Ld.prototype.format=gvjs_Ld.prototype.format;gvjs_Ld.Format={FULL_DATE:0,LONG_DATE:1,MEDIUM_DATE:2,SHORT_DATE:3,FULL_TIME:4,LONG_TIME:5,MEDIUM_TIME:6,SHORT_TIME:7,FULL_DATETIME:8,LONG_DATETIME:9,MEDIUM_DATETIME:10,SHORT_DATETIME:11};var gvjs_ce=gvjs_Rd;gvjs_Yd.Format={DECIMAL:1,SCIENTIFIC:2,PERCENT:3,CURRENCY:4,COMPACT_SHORT:5,COMPACT_LONG:6};gvjs_Yd.prototype.format=gvjs_Yd.prototype.format;gvjs_Yd.prototype.setMinimumFractionDigits=gvjs_Yd.prototype.setMinimumFractionDigits;
gvjs_Yd.prototype.setMaximumFractionDigits=gvjs_Yd.prototype.setMaximumFractionDigits;gvjs_Yd.prototype.setSignificantDigits=gvjs_Yd.prototype.setSignificantDigits;gvjs_Yd.setEnforceAsciiDigits=function(a){gvjs__d=a};gvjs_Yd.isEnforceAsciiDigits=function(){return gvjs__d};var gvjs_de=gvjs_Wd;gvjs_Id.createTimeZone=gvjs_Jd;function gvjs_ee(){}gvjs_ee.prototype.ac=function(a){return this.qO(a)};function gvjs_fe(a){this.init(a)}gvjs_l(gvjs_fe,gvjs_ee);gvjs_fe.prototype.init=function(a){a=new gvjs_qd([a||{},{formatType:gvjs__a,valueType:gvjs_Pa}]);this.gd=a.ea(gvjs_Xa);this.Pb=null;this.coa=a.ob("formatType",gvjs_Gaa);this.Tya=a.ob("valueType",gvjs_ge);this.rla=gvjs_s(a,"clearMinutes",!1);this.bga=null;a=a.Da("timeZone");null!=a&&(this.bga=gvjs_Id.createTimeZone(60*-a))};
var gvjs_he=gvjs_Ld.Format,gvjs_Gaa={aAa:gvjs_Sa,zAa:"long",FAa:gvjs_Va,SHORT:gvjs__a},gvjs_ge={Qha:gvjs_Oa,Rha:gvjs_Pa,HBa:"time"};
function gvjs_Haa(a,b){switch(a){case gvjs_Oa:switch(b){case gvjs_Sa:return gvjs_Ld.Format.FULL_DATE;case "long":return gvjs_Ld.Format.LONG_DATE;case gvjs_Va:return gvjs_Ld.Format.MEDIUM_DATE;case gvjs__a:return gvjs_Ld.Format.SHORT_DATE}case gvjs_Pa:switch(b){case gvjs_Sa:return gvjs_Ld.Format.FULL_DATETIME;case "long":return gvjs_Ld.Format.LONG_DATETIME;case gvjs_Va:return gvjs_Ld.Format.MEDIUM_DATETIME;case gvjs__a:return gvjs_Ld.Format.SHORT_DATETIME}case "time":switch(b){case gvjs_Sa:return gvjs_Ld.Format.FULL_TIME;
case "long":return gvjs_Ld.Format.LONG_TIME;case gvjs_Va:return gvjs_Ld.Format.MEDIUM_TIME;case gvjs__a:return gvjs_Ld.Format.SHORT_TIME}default:return gvjs_Ld.Format.FULL_DATETIME}}gvjs_fe.prototype.Bm=gvjs_f(16);gvjs_fe.prototype.format=function(a,b){var c=gvjs_xd(a.Y(b),gvjs_ge);if(c==gvjs_Oa||c==gvjs_Pa){c=this.pN(c);for(var d=a.aa(),e=0;e<d;e++){var f=a.getValue(e,b);f=gvjs_ie(this,c,f);gvjs_j(a.yp)&&a.yp(e,b,f)}}};
gvjs_fe.prototype.qO=function(a){this.Pb||(this.Pb=this.pN(this.Tya));return gvjs_ie(this,this.Pb,a)};gvjs_fe.prototype.pN=function(a){var b=this.gd;null==b&&(b=gvjs_Haa(a,this.coa));return new gvjs_Ld(b)};function gvjs_ie(a,b,c){if(null===c)return"";var d=a.bga;null==d&&(d=gvjs_Id.createTimeZone(c.getTimezoneOffset()));c=new Date(c.getTime());a.rla&&c.setMinutes(0);return b.format(c,d)};function gvjs_je(a){var b=new gvjs_qd([a||{},{decimalSymbol:gvjs_ke,groupingSymbol:gvjs_le,fractionDigits:2,significantDigits:null,negativeParens:!1,prefix:"",suffix:"",scaleFactor:1}]);this.wy=gvjs_Ed(b,"fractionDigits");a&&typeof a.fractionDigits===gvjs_c&&isNaN(a.fractionDigits)&&(this.wy=NaN);this.Cm=b.LC("significantDigits");this.nma=gvjs_r(b,"decimalSymbol");this.IY=gvjs_r(b,"groupingSymbol");this.Ada=gvjs_r(b,gvjs_Ya);this.Pfa=gvjs_r(b,gvjs_1a);this.rca=b.cz("negativeColor");this.sca=gvjs_s(b,
"negativeParens");(this.gd=b.ob(gvjs_Xa))&&this.gd.toLowerCase()in gvjs_me&&(this.gd=gvjs_me[this.gd.toLowerCase()]);this.qK=gvjs_t(b,"scaleFactor");if(0>=this.qK)throw Error("Scale factor must be a positive number.");this.Pb=null}gvjs_l(gvjs_je,gvjs_ee);
var gvjs_me={decimal:gvjs_Yd.Format.DECIMAL,scientific:gvjs_Yd.Format.SCIENTIFIC,percent:gvjs_Yd.Format.PERCENT,currency:gvjs_Yd.Format.CURRENCY,"short":gvjs_Yd.Format.COMPACT_SHORT,"long":gvjs_Yd.Format.COMPACT_LONG},gvjs_ne=!1,gvjs_ke=gvjs_de.DECIMAL_SEP,gvjs_le=gvjs_de.GROUP_SEP,gvjs_oe=gvjs_de.DECIMAL_PATTERN;
gvjs_je.prototype.format=function(a,b){if(a.Y(b)==gvjs_c)for(var c=0;c<a.aa();c++){var d=a.getValue(c,b);if(null!=d){var e=this.ac(d);gvjs_j(a.yp)&&a.yp(c,b,e);gvjs_j(a.setProperty)&&!gvjs_Rb(gvjs_dc(this.rca))&&0>d&&a.setProperty(c,b,gvjs_0a,gvjs_Na+this.rca+";")}}};
gvjs_je.prototype.qO=function(a){var b=a/this.qK;if(null!==this.gd){a=gvjs_Yd.isEnforceAsciiDigits();gvjs_Yd.setEnforceAsciiDigits(!gvjs_ne);var c=new gvjs_Yd(this.gd);this.gd!=gvjs_Yd.Format.COMPACT_SHORT&&this.gd!=gvjs_Yd.Format.COMPACT_LONG||c.setSignificantDigits(3);this.Pb=c;null!=this.Cm&&(c.setSignificantDigits(this.Cm),c.setMaximumFractionDigits(this.Cm));b=c.format(b);b=this.Ada+b+this.Pfa;gvjs_Yd.setEnforceAsciiDigits(a)}else{if(isNaN(this.wy))return String(a);this.sca&&(b=Math.abs(b));
c=b;0==this.wy&&(c=Math.round(c));b=[];0>c&&(c=-c,b.push("-"));var d=Math.pow(10,this.wy),e=Math.round(c*d);c=String(Math.floor(e/d));d=String(e%d);if(3<c.length&&this.IY)for(e=c.length%3,0<e&&(b.push(c.substring(0,e),this.IY),c=c.substring(e));3<c.length;)b.push(c.substring(0,3),this.IY),c=c.substring(3);b.push(c);0<this.wy&&(b.push(this.nma),d.length<this.wy&&(d=gvjs_ea+d),b.push(d.substring(d.length-this.wy)));b=b.join("");b=this.Ada+b+this.Pfa;this.sca&&0>a&&(b="("+b+")")}return b};
gvjs_je.prototype.parse=function(a){if(this.Pb&&this.Pb.parse){var b=gvjs_Yd.isEnforceAsciiDigits();gvjs_Yd.setEnforceAsciiDigits(!gvjs_ne);a=this.Pb.parse(a);gvjs_Yd.setEnforceAsciiDigits(b);return a}throw Error("Cannot parse without parser.");};function gvjs_pe(a){this.m=a||{}}gvjs_pe.prototype.format=function(a,b){if(a.Y(b)==gvjs_c)for(var c=this.m.base||0,d=0;d<a.aa();d++){var e=a.getValue(d,b);e=e<c?"google-visualization-formatters-arrow-dr":e>c?"google-visualization-formatters-arrow-ug":"google-visualization-formatters-arrow-empty";gvjs_j(a.setProperty)&&a.setProperty(d,b,gvjs_Ma,e)}};function gvjs_qe(a){this.m=a||{}}var gvjs_Iaa={red:"r",blue:"b",green:"g"};function gvjs_re(a,b,c){0<b&&c.push('<span class="google-charts-bar-'+(a||"w")+'" style="width:'+b+'px;"></span>')}
gvjs_qe.prototype.format=function(a,b){if(a.Y(b)==gvjs_c){var c=this.m,d=c.min,e=c.max,f=null;if(null==d||null==e)f=a.Zj(b),null==e&&(e=f.max),null==d&&(d=Math.min(0,f.min));d>=e&&(f=f||a.Zj(b),e=f.max,d=f.min);d==e&&(0==d?e=1:0<d?d=0:e=0);f=e-d;var g=c.base||0;g=Math.max(d,Math.min(e,g));var h=c.width||100,k=c.showValue;null==k&&(k=!0);for(var l=Math.round((g-d)/f*h),m=h-l,n=0;n<a.aa();n++){var p=a.getValue(n,b),q=[];p=Math.max(d,Math.min(e,p));var r=Math.ceil((p-d)/f*h);q.push('<span class="google-visualization-formatters-bars">');
gvjs_re("s",1,q);var t=gvjs_se(c.colorPositive,"b"),u=gvjs_se(c.colorNegative,"r"),v=c.drawZeroLine?1:0;0<l?p<g?(gvjs_re("w",r,q),gvjs_re(u,l-r,q),0<v&&gvjs_re("z",v,q),gvjs_re("w",m,q)):(gvjs_re("w",l,q),0<v&&gvjs_re("z",v,q),gvjs_re(t,r-l,q),gvjs_re("w",h-r,q)):(gvjs_re(t,r,q),gvjs_re("w",h-r,q));gvjs_re("s",1,q);p=a.getProperty(n,b,gvjs_Ha);null==p&&gvjs_j(a.setProperty)&&(p=a.Ga(n,b),a.setProperty(n,b,gvjs_Ha,p));k&&(q.push("\u00a0"),q.push(p));q.push("</span>\u00a0");gvjs_j(a.yp)&&a.yp(n,b,q.join(""))}}};
function gvjs_se(a,b){a=(a||"").toLowerCase();return gvjs_Iaa[a]||b};function gvjs_te(a,b,c,d){gvjs_sb(a)&&(a=a.getTime());gvjs_sb(b)&&(b=b.getTime());Array.isArray(a)&&(a=gvjs_ue(a));Array.isArray(b)&&(b=gvjs_ue(b));this.UX=a;this.c4=b;this.Ik=c;this.zx=d}gvjs_te.prototype.contains=function(a){var b=this.UX,c=this.c4;if(null==a)return null==b&&null==c;gvjs_sb(a)?a=a.getTime():Array.isArray(a)&&(a=gvjs_ue(a));return(null==b||a>=b)&&(null==c||a<c)};gvjs_te.prototype.je=function(){return this.Ik};gvjs_te.prototype.getBackgroundColor=function(){return this.zx};
function gvjs_ve(a,b,c,d,e){gvjs_te.call(this,a,b,c,"");this.u1=b-a;0>=this.u1&&(this.u1=1);this.foa=gvjs_ad(gvjs_6c(d).hex);this.dya=gvjs_ad(gvjs_6c(e).hex)}gvjs_l(gvjs_ve,gvjs_te);gvjs_ve.prototype.getBackgroundColor=function(a){if(typeof a!==gvjs_c)return"";a=gvjs_cd(this.foa,this.dya,1-(a-this.UX)/this.u1);return gvjs_bd(a[0],a[1],a[2])};function gvjs_we(){this.CR=[]}gvjs_we.prototype.addRange=function(a,b,c,d){this.CR.push(new gvjs_te(a,b,c,d))};
gvjs_we.prototype.Mja=function(a,b,c,d,e){this.CR.push(new gvjs_ve(a,b,c,d,e))};gvjs_we.prototype.format=function(a,b){var c=a.Y(b);if(c==gvjs_c||c==gvjs_e||c==gvjs_Oa||c==gvjs_Pa||c==gvjs_2a)for(c=0;c<a.aa();c++){for(var d=a.getValue(c,b),e="",f=0;f<this.CR.length;f++){var g=this.CR[f];if("undefined"!==typeof d&&g.contains(d)){f=g.je();d=g.getBackgroundColor(d);f&&(e+=gvjs_Na+f+";");d&&(e+=gvjs_Ja+d+";");break}}gvjs_j(a.setProperty)&&a.setProperty(c,b,gvjs_0a,e)}};
function gvjs_ue(a){return 36E5*a[0]+6E4*a[1]+1E3*a[2]+(4==a.length?a[3]:0)};function gvjs_xe(a){this.gd=a||""}function gvjs_Jaa(a,b,c,d,e,f,g){return 0<f&&"\\"==g[f-1]?d:b.Ga(a,c[parseInt(e,10)])}gvjs_xe.prototype.format=function(a,b,c,d){var e=b[0];null!=c&&gvjs_qb(c)==gvjs_c&&(e=c);c=d||null;for(d=0;d<a.aa();d++){var f=this.gd.replace(/{(\d+)}/g,gvjs_ub(gvjs_Jaa,d,a,b));f=f.replace(/\\(.)/g,"$1");c&&gvjs_j(a.setProperty)?a.setProperty(d,e,c,f):gvjs_j(a.yp)&&a.yp(d,e,f)}};gvjs_h(gvjs_Ta,gvjs_je,void 0);gvjs_je.prototype.format=gvjs_je.prototype.format;gvjs_je.prototype.formatValue=gvjs_je.prototype.ac;gvjs_h("google.visualization.NumberFormat.useNativeCharactersIfAvailable",function(a){gvjs_ne=a},void 0);gvjs_h("google.visualization.NumberFormat.DECIMAL_SEP",gvjs_ke,void 0);gvjs_h("google.visualization.NumberFormat.GROUP_SEP",gvjs_le,void 0);gvjs_h("google.visualization.NumberFormat.DECIMAL_PATTERN",gvjs_oe,void 0);
gvjs_h("google.visualization.ColorFormat",gvjs_we,void 0);gvjs_we.prototype.format=gvjs_we.prototype.format;gvjs_we.prototype.addRange=gvjs_we.prototype.addRange;gvjs_we.prototype.addGradientRange=gvjs_we.prototype.Mja;gvjs_h("google.visualization.BarFormat",gvjs_qe,void 0);gvjs_qe.prototype.format=gvjs_qe.prototype.format;gvjs_h("google.visualization.ArrowFormat",gvjs_pe,void 0);gvjs_pe.prototype.format=gvjs_pe.prototype.format;gvjs_h("google.visualization.PatternFormat",gvjs_xe,void 0);
gvjs_xe.prototype.format=gvjs_xe.prototype.format;gvjs_h("google.visualization.DateFormat",gvjs_fe,void 0);gvjs_fe.prototype.format=gvjs_fe.prototype.format;gvjs_fe.prototype.formatValue=gvjs_fe.prototype.ac;gvjs_h(gvjs_Ta,gvjs_je,void 0);gvjs_je.prototype.format=gvjs_je.prototype.format;gvjs_h("google.visualization.TableColorFormat",gvjs_we,void 0);gvjs_h("google.visualization.TableBarFormat",gvjs_qe,void 0);gvjs_qe.prototype.format=gvjs_qe.prototype.format;
gvjs_h("google.visualization.TableArrowFormat",gvjs_pe,void 0);gvjs_pe.prototype.format=gvjs_pe.prototype.format;gvjs_h("google.visualization.TablePatternFormat",gvjs_xe,void 0);gvjs_xe.prototype.format=gvjs_xe.prototype.format;gvjs_h("google.visualization.TableDateFormat",gvjs_fe,void 0);
